### ISSUE TITLE
improve content authoring experience for non-coders

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#10]
## Prose

http://prose.io is a markdown editor that commits to github. Supports image uploading, metadata editing, preview. It's pretty lightweight, but smooth UI.
## Prismic

https://prismic.io is a service where you can author content. It can be queried via an API.
https://prismic.io/tour/writing-room
Content can be related, and there are fancy AB options.
metalsmith plug-in: https://www.npmjs.com/package/metalsmith-prismic
## Contentful

https://www.contentful.com is another similar authoring service. The API also supports importing content, like from a legacy system: https://www.contentful.com/developers/
https://github.com/contentful/contentful-metalsmith
## RSS

metalsmith seems to fall down here 
Jekyll seems to have more tools for this

**Comment by andrewmallis** [comment]
signed up for a prismic account:
https://kalastatic.prismic.io/timeline/
motivated to try this out in a branch
I can add collaborators upon request

**Comment by RobLoach** [comment]
I like Prismic's UI. If we have a number of different importers available, we could essentially have content coming from anywhere.

**Comment by pirog** [comment]
Import everything. Maybe it's time to hire Art Vandalay inc to help?

On Wednesday, February 4, 2015, Rob Loach <notifications@github.com> wrote:

> I like Prismic's UI. If we have a number of different importers available,
> we could essentially have content coming from anywhere.
>
> —
> Reply to this email directly or view it on GitHub.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by madeofpeople** [comment]
I thought they were Architects ;)

**Comment by pirog** [comment]
i thought they were importer exporters?

On Wed, Feb 4, 2015 at 11:20 AM, Thiago de Mello Bueno <
notifications@github.com> wrote:

> I thought they were Architects ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/10#issuecomment-72919708>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
I thought they dealt in latex

**Comment by pirog** [comment]
![image](https://cloud.githubusercontent.com/assets/713424/6049404/e9e9a75e-ac6b-11e4-9ea5-6a5d8a80c2db.png)

**Comment by andrewmallis** [comment]
@RobLoach  can you please investigate prismic. Feel free to spawn a dedicated issue if more appropriate.

**Comment by RobLoach** [comment]
Metalsmith-Prismatic is now updated to the latest version of Metalsmith, and passing tests. Moving it to the latest verison of Prismic API is next.

**Comment by madeofpeople** [comment]
There's some low-hanging possibilities discussed here #110

**Comment by RobLoach** [comment]
Prismic demo PR... Going to open up a multidev for it.

**Comment by andrewmallis** [comment]
https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#multidev/overview/git-branches

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/94
http://prismic-kalastatic.at.kalamuna.com/news/

**Comment by RobLoach** [comment]
Some content providers we could have:

- [ ] RSS
- [ ] Drupal 8 HAL/JSON

**Comment by thiagodemellobueno** [comment]
Between KSS3.0 Json files and #363  we would have some real chance at making this almost trivial
