### ISSUE TITLE
Carousel should go in examples section

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#101]
I think there was a comment to this affect somewhere but I think it got missed. We don't want a main nav item for it, it belongs in the styleguide components.

**Comment by soniktrooth** [comment]
So the bootstrap carousel is already in the style guide (albeit not really working properly) and I realised that what this is here for is actually as an example of a collection turning into a working carousel. 

Perhaps what we really want is an examples section to the site. 

Thoughts?

**Comment by andrewmallis** [comment]
Each section of the site in an example of things, and the styleguide also provides some examples, but these don't contain content as you say.

Any thoughts on why the slideshow in the guide is not as pretty as the one http://0.0.0.0:8000/carousel ?

It's probably valuable to have a slideshow example in a component section, and we talk about this in #84 more. I don't particularly like a single menu item for the slideshow, and I'm guessing you don't either. In the interim, I am ok with relabelling this to examples temporarily.

**Comment by RobLoach** [comment]
Kind of working:
http://dev-kalastatic.at.kalamuna.com/styleguide/section-3.html#3.6

**Comment by soniktrooth** [comment]
Changing tacts here. We want to add an examples section where we can house examples of things that are too complex for the style guide

**Comment by RobLoach** [comment]
QA: https://github.com/kalamuna/kalastatic/blob/master/templates/examples.html
