### ISSUE TITLE
Lots of 404s

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#105]
There's a bunch of 404s being thrown in the inspector for missing js and font files.

Pretty much any page is missing:
- bootstrap.js
- holder.js
- jquery.matchHeight.js
- jquery.min.js

I assume this stuff is being inlined in scripts.js or the site wouldn't work. 

On styleguide pages we're getting 404s for 
- sourcesanspro-bold.woff
- sourcesanspro-regular.woff

**Comment by RobLoach** [comment]
Related: https://github.com/kalamuna/kalastatic/issues/65

**Comment by andrewmallis** [comment]
also #138 – we should only have one?

**Comment by madeofpeople** [comment]
This is in the styleguide? Or both the styleguide and the metalsmith?

**Comment by soniktrooth** [comment]
This is fixed
