### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#108]
We need to make sure that each time we deploy caches for items that have changed are cleared.

In kcom we implemented this for css/js by creating a variable sitemeta.cachebuster that stores a unique key (i used the date, we can use semver or more sophisticated approaches) and appending that variable to the querystring of those assets.
```
main.css?{{sitemeta.cachebuster}} ----> main.css?04.28.2015
```

Here are some other possible solutions, that may automate this process a bit.
https://www.npmjs.com/package/grunt-cachebust-plus
https://www.npmjs.com/package/cache-bust
https://www.npmjs.com/package/cache-breaker

**Comment by andrewmallis** [comment]
bringing this in to 0.3 since we implemented this in pinnacle.
@RobLoach may have some feedback on the approach

**Comment by madeofpeople** [comment]
Implemented this via [metasmith-swig-helpers](https://www.npmjs.com/package/metalsmith-swig-helpers)

```{{'/js/scripts.js'|bustcache}}`` appends '?' + ms-since-unix-expo to the string in question at bruild-time effectively making sure such assets are not cached.

Added an entry to the wiki here https://github.com/kalamuna/kalastatic/wiki/Cache-Busting
