### ISSUE TITLE
improve styleguide docs navigation

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#11]
we've been adding a 4th menu item at
https://github.com/kalamuna/kalastatic/blob/master/styleguide/styleguide.md
to point to site specific components.

We should more clearly identify that components and CSS are Bootstrap-specific also by relabelling them.

A stub for the project's components should also be in the project start state.

**Comment by andrewmallis** [comment]
Not sure if this is still relevant. In QA for you @RobLoach

**Comment by andrewmallis** [comment]
![style_guide](https://cloud.githubusercontent.com/assets/249362/8682429/c9430728-2a21-11e5-9f17-318f047b6b04.png)

**Comment by RobLoach** [comment]
Home link is at:
https://github.com/kalamuna/kss-bootstrap/blob/master/bootstrap/index.html#L28

**Comment by andrewmallis** [comment]
let's update the kss-boostrap with a more official version, then merge that in.
putting to in progress in the interim

**Comment by andrewmallis** [comment]
also, as per image above, can we make the custom components link last, after fontawesome?

**Comment by andrewmallis** [comment]
relates to #152

**Comment by RobLoach** [comment]
Did we decide what "Custom Components" should be renamed to?
http://dev-kalastatic.at.kalamuna.com/styleguide/section-5.html

**Comment by andrewmallis** [comment]
Things are now looking good and we have the intended order.

As per @RobLoach's question,
"Custom Components" has been suggested renamed to "Components" with some break-out organism, molecule, atom subnav items by @madeofpeople – once we fully realize this paradigm.

This would leave us with 2 menu items labelled "Components" and we have suggested identifying the framework elements more clearly –
perhaps by wrapping the CSS, Components, and Javascript items into a thin outlined box, prefixed with the Boostrap icon.

Worth keeping in mind that not all styleguides may be bootstrap.


Still, it is a bit awkward to have 2 nav items identically named…

Perhaps this question should be broken out into another more focused issue?

**Comment by madeofpeople** [comment]
Cant we just call it “bootstrap?”

**Comment by andrewmallis** [comment]
Bootstrap in this context applies to CSS, Components, and Javascript – not just to Components…
