### ISSUE TITLE
Bring in scss linting

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#112]

**Comment by madeofpeople** [comment]
Currently with bootstrap dependencies the standard csslint rules give some 584 warnings, so it's unclear how useful this is.

71 !importants (our code counts three of those)

Too many font-size declarations (60), abstraction needed.

You have 7 h1s, 6 h2s, 6 h3s, 4 h4s, 3 h5s, 3 h6s defined in this stylesheet.
RojoAir-2:kalastatic thiago$ npm install sass-lint

We cant separate bootstrap out entire or anything that extends column classes and such would not have an object to @extend.\

Eventually we'll be able to lint our SASS using: https://github.com/sasstools/sass-lint
but it's not ready for primetime yet. 

Staying in the backlog.

**Comment by madeofpeople** [comment]
Also eventually we will want to use https://github.com/sasstools/sass-lint for our Sass

**Comment by madeofpeople** [comment]
Sass lint is ready to roll https://github.com/sasstools/sass-lint/releases 
at version 1.31

**Comment by RobLoach** [comment]
Code analysis and linting on the SASS would help us a lot.

**Comment by soniktrooth** [comment]
I have done some work in DENT and EECS to get this off the ground. I will add a PR at some point soon.

**Comment by andrewmallis** [comment]
renaming issue to link ths scss instead.

DENT work mentioned by @soniktrooth = https://github.com/ucsf-dent/dentalcenter/pull/54/files

**Comment by soniktrooth** [comment]
Still a work in progress, probs best to link to the file itself: https://github.com/ucsf-dent/dentalcenter/blob/bd1a9cb88a3b378af87ec7b61ef147334a823a3c/sites/all/themes/dentc/kalastatic/.sass-lint.yml

**Comment by thiagodemellobueno** [comment]
We're ready to move on this one yes @josh?

**Comment by soniktrooth** [comment]
yes @thiagodemellobueno

**Comment by thiagodemellobueno** [comment]
@soniktrooth rocked this hard.


![](http://66.media.tumblr.com/da82fff3f7708cbece254e9c89067c5a/tumblr_nvfxd4uJU81sa1ef5o1_500.jpg)
