### ISSUE TITLE
Visual Regression Testing

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#114]
http://www.gizra.com/content/visual-regression-travis-shoov-ngrok

pulls it all together. Looks exciting and possible.

**Comment by madeofpeople** [comment]
https://github.com/garris/BackstopJS
?

**Comment by RobLoach** [comment]
http://bbc-news.github.io/wraith/ is the one.

**Comment by soniktrooth** [comment]
https://github.com/Huddle/PhantomCSS is a casper.js module. Easier to set up because no ruby?

**Comment by RobLoach** [comment]
https://github.com/cheeaun/puppetron

**Comment by RobLoach** [comment]
https://pantheon.io/blog/automating-wordpress-core-and-plugin-updates-visual-regression-testing

**Comment by RobLoach** [comment]
Cleaning up this backlog here. Will likely re-open this issue or make a new one. Stay tuned.
