### ISSUE TITLE
Problem building Metalsmith 

### ISSUE THREAD

**Issue by rcross** [kalamuna/kalastatic#116]
When doing an install and build, I'm getting: 

 Metalsmith · failed to require plugin "metalsmith-sass".

I found that I needed to: 

1) install grunt globally (sudo npm install -g grunt-cli)
2) install metalsmith (sudo npm install metalsmith)
3) install metalsmith_sass (sudo npm install --save metalsmith-sass)

Then I could run npm run-script build without errors.

**Comment by labboy0276** [comment]
You should never run npm commands with sudo after initial install as a FYI.  

Use this:
https://github.com/mattgrill/NPM-Doctor

It fixes a fail in npm install and should alleviate a most odd node problems you have.

**Comment by RobLoach** [comment]
What environment are you on?

**Comment by rcross** [comment]
osx 10.10.2

I've had quite a few errors (or just stalls) when trying to run things without sudo.

**Comment by rcross** [comment]
I've installed/run the npm-doctor util. As things are already installed now, I'm not sure I can test things without sudo. Either way, the error(s) don't seem to be related to my sudo usage.

**Comment by madeofpeople** [comment]
@rcros to build kalastatic you should only need to do the following steps:
```npm install -g grunt``` 
(You only need this step if you haven't yet I stalled grunt)
Then
```npm install```
This installs all other dependencies and runs bower install.

That's it. You don't need to install metalsmith sass and metalsmith separately.

**Comment by rcross** [comment]
i was still getting the "Metalsmith · failed to require plugin "metalsmith-sass"." error after installing grunt globally and running npm install. Hence why I tried to manually install both to get around the error.

**Comment by rcross** [comment]
I followed the steps in the documentation. 
rather than telling me I shouldn't have taken the steps I did (which I took b/c of the error), can anyone try replicating the error, perhaps on a fresh vm?

**Comment by madeofpeople** [comment]
@rcross, we're trying to help, thanks for you patience.
Please provide the version of node you are using, and the version of npm

**Comment by rcross** [comment]
npm - 2.10.1
node - v0.12.4

No worries, just trying not to let the issue get distracted. I think its likely a small fix to the build script (or the documentation instructions) but I don't know how to debug or what the fix would be.

**Comment by rcross** [comment]
grunt - v0.1.13 in case that matters

**Comment by RobLoach** [comment]
``` bash
node --version
v0.12.4
npm --version
2.10.1
git clone git@github.com:kalamuna/kalastatic.git
cd kalastatic
npm install
npm test
```

Builds here okay... Could you try deleting your `node_modules` and `~/.npm` and then trying again? Permissions can get weird sometimes, I understand.

**Comment by madeofpeople** [comment]
@rcross did you have any luck?

**Comment by RobLoach** [comment]
node-sass fixed some things to have node 4 work. Could you try it again with the latest version of node?

**Comment by RobLoach** [comment]
Closing for now, feel free to re-open if the issue persists.
