### ISSUE TITLE
Document creating and upgrading Kalastatic once it lives in Drupal

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#117]
Once we put kalastatic in a Drupal context, it's been decoupled from the main repo. Until we have a full on CLI approach, we need to document how to bring kalastatic up to speed when new improvements come out from this repo.

**Comment by andrewmallis** [comment]
We're currently facing these challenges on the kalastatic+kalatheme test bed.

**Comment by andrewmallis** [comment]
@RobLoach & @soniktrooth – I think we're due to update the testbed again with recent improvements. A good opportunity to kickstart this documentation.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/wiki/Upgrading-in-KalaTheme

http://kalastatic-kalatheme.at.kalamuna.com/sites/all/themes/kt_sub/kalastatic/build/index.html

**Comment by RobLoach** [comment]
the mallIs menTIOned brANd cAsing.... May or may not be something critical to the completion of this docuMENTATION.

**Comment by andrewmallis** [comment]
Yeah, I am on your case…

Edited this one for consistency; added a bit of clarifying language:
https://github.com/kalamuna/kalastatic/wiki/Integrating-Kalastatic-with-Kalatheme

**Comment by RobLoach** [comment]
Edited case of the other:
https://github.com/kalamuna/kalastatic/wiki/Upgrading-in-Kalatheme

**Comment by andrewmallis** [comment]
that page is now:
https://github.com/kalamuna/kalastatic/wiki/Upgrading-an-existing-Kalastatic-Kalatheme-installation

``git diff`` seems like a pain, yeah. Looks like it might take some pretty major re-architecting to make this more seamless, even in a CLI context. Dunno. Would like to get your thoughts in convo.

We should probably link to these pages to the drupal module docs…

**Comment by andrewmallis** [comment]
I was going to suggest with reference this in the kalastatic module docs, but I am not certain that will be so useful. @soniktrooth – thoughts?

**Comment by soniktrooth** [comment]
Def can't hurt to reference this from the module. I will get about it.

**Comment by soniktrooth** [comment]
https://github.com/kalamuna/kalastatic_dot_module/commit/1e828be5bf1d47fcc1f28ed47593a9cdea3ec72a

**Comment by RobLoach** [comment]
Closing this one. We have kstat_dot_module, and the wiki page.
