### ISSUE TITLE
run kss templates through metalsmith

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#12]
@robloach you mentioned wanting to run kss innards through the metalsmith so the styleguide loads within the site. I'm just making sure we're keeping not losing track of this desire.

**Comment by andrewmallis** [comment]
:+1:

**Comment by madeofpeople** [comment]
#178 means we can continue to not worry about KSS being handlebars driven.

Still a little more  styleguide / proto / kstatic harmony maybe good.

I also think we should put code examples in collapsable drawers or modals.

**Comment by RobLoach** [comment]
Another discussion is improving metalsmith-kss and having that create the styleguide for us.

**Comment by thiagodemellobueno** [comment]
Kill it with fire.
