### ISSUE TITLE
update pantheon with latest code

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#121]
I'd like to have a public example of kalastatic on pantheon.
We have some issues with the CI currently.
In the meanwhile can you push the 0.2.5 tag up and any other tagged releases – in particular this 0.3 target.

**Comment by RobLoach** [comment]
http://dev-kalastatic.at.kalamuna.com

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/95
