### ISSUE TITLE
use SVG logo by default

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#13]

**Comment by soniktrooth** [comment]
@andrewmallis can you elaborate on this one? Anyone can just change the .logo background image to use logo.svg instead of logo.png so I'm not sure how you want to 'support' SVG.

**Comment by andrewmallis** [comment]
we should ship with SVG by default

**Comment by soniktrooth** [comment]
As we discovered over on kalamuna.com, the KalaGem™ is problematic in SVG. We ended up running with a @2x png over there, wondering what we should do over here. 

My thinking is that an SVG logo is preferable and I doubt we'd have the same probs with too many other logos so maybe we should run with something other than the kalamuna logo so it can be SVG. Maybe kalastatic needs it's own logo.

**Comment by andrewmallis** [comment]
Kalastatic needs its own logo

**Comment by andrewmallis** [comment]
static in the gem would probably blow the SVG option,
but we can generate text for "kalastatic" as an SVG.

**Comment by RobLoach** [comment]
:+1: 

Did we choose which minimal browsers we support?
