### ISSUE TITLE
JS 404s

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#138]
The following files are attempting to be included but I'm pretty sure we're already manually rolling them into our own js: 

• boostrap.js
• holder.js
• jquery.matchHeight.js
• jquery.min.js

**Comment by RobLoach** [comment]
The `browserify` branch fixes this by moving to a module-loader. https://github.com/kalamuna/kalastatic/pull/139

Would appreciate testing/QA.

**Comment by soniktrooth** [comment]
@RobLoach Does that mean we're no longer rolling it all into one big js file?

**Comment by RobLoach** [comment]
> @RobLoach Does that mean we're no longer rolling it all into one big js file?

[Browserify](http://browserify.org/) compiles all the JavaScript files into one big js file for us, resolving any `require('module')`'s into browser-usable code.

**Comment by madeofpeople** [comment]
How does this play with the styleguide?

**Comment by RobLoach** [comment]
No more 404s.

**Comment by soniktrooth** [comment]
Duplicated in #105
