### ISSUE TITLE
audit kalamuna.com for awesomeness

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#14]
https://github.com/kalamuna/kalamuna.com
there are things in there the base should have.

**Comment by madeofpeople** [comment]
Initial sensor sweeps show that we maybe at a point where we've left kala.com behind, but I'll take a pass later today.

**Comment by madeofpeople** [comment]
The only thing that comes to mind is 
Breakpoint detection in JS  http://bjork24.github.io/Unison/ which is useful, but not necessarily universally needed.

**Comment by andrewmallis** [comment]
closing the issue in this context
