### ISSUE TITLE
Redesign as KalaStatic Framework

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#141]
After some discussion with Thiago, I thought I'd do a brain-dump and thought experiment for a redesign of some things I had on my mind. The aim is to simplify KalaStatic, make it easier to use, deploy, and adopt. Make it less of a boilerplate, and more of a framework/product. Some of the ideas presented here are taken from other systems out there. This changes some of the workflows and ideas in an effort to make it simpler and more flexible...
### Goals
- Data in files rather than split across configuration package.json, metalsmith.json, etc
- Default configuration set, provide features automagically, no knowledge of Metalsmith required
- Only one public directory (keep it simple and have all source in one directory - no templates dir)
### Sample File Structure

```
package.json               Any global additional configuration - loaded into globals
public/                    Any public files
public/sample.html.md      Uses Markdown to output a sample.html file
public/example.html.md     Uses Markdown
public/_layout.swig        A template, which uses Swig when processing
public/_mypartial.ejs      A partial, which is rendered using EJS
public/main.css.scss       SCSS, which outputs to main.css
public/main.js.uglify-js.duo   Process the content with Duo, then UglifyJS it to main.js
```
##### sample.html.md

``` markdown
# Sample

Hello, this is a sample
```
##### example.html.md

``` markdown

---
title: Example
template: _layout

---

Why **hello** there!
```
##### _layout.swig

``` html
<!doctype html>
<html>
<head>
<title>{{ title }}</title>
</head>
<body>
<div class="content"> {{ content }} </div> <-- content is the rendered output from example.html.md
<div class="partial"> {{ _mypartial }} </div>
</body>
</html>
```
##### _mypartial.ejs

``` ejs
<h1><%= title %></h1>
```
##### main.js.uglify-js.duo

``` js
var uid = require('matthewmueller/uid');
var fmt = require('yields/fmt');

var msg = fmt('Your unique ID is %s!', uid());
window.alert(msg);
```
##### main.css.scss

``` sass

---
scss:
  outputStyle: nested
  sourceComments: true
  sourceMap: true
  includePaths:
    - "assets/vendor"

---
@import "bootstrap";
@import "fontawesome";

body {
  background-color: red;
}
```
### What's Needed?

This would require the development of a number of different Metalsmith plugins to make its composition. A lot of it is actually already possible in some existing plugins, with a given configuration. Some notes:
- Don't output files that start with `_`. Instead, load them in as globals
  - This could be handled by metalsmith-ignore, which `_*` as the config, but we still want to load them in as globals
- Recursive file extension rendering (i.e. main.js.uglify-js.duo)
  - The options for compiling are taken from the file's meta-data with the name of the engine
- Rethink of `metalsmith-templates` to have templates in the source directory (select the template from the file's `template:` meta-data)

**Comment by reynoldsalec** [comment]
@RobLoach I think this is a really good vision for one future of KalaStatic. Are you considering this within the current scope of cleaning-up KalaStatic, or is this just a brain-dump for future implementation?

**Comment by RobLoach** [comment]
@reynoldsalec I believe just a brain-dump for now. Considering the flexibility of Metalsmith, this would be a rolling target, bringing in plugins one at a time leading us to where we want to be.

In its current state, KalaStatic is a boilerplate project. It is great if you're starting a new site. The result, however, is that upgrades become difficult. Adopting file conventions over configuration mean KalaStatic can be upgraded easily, without worrying about configuration conflicts at all.

KalaStatic essentially evolved from being a Boilerplate project, into a set of Metalsmith plugins, with a default set of configuration.

**Comment by andrewmallis** [comment]
some awesomeness is here: https://github.com/kalamuna/kalastatic-cli

**Comment by madeofpeople** [comment]
@RobLoach YAS!

**Comment by thiagodemellobueno** [comment]
Should we just rename this issue "Kalastatic 2"

**Comment by RobLoach** [comment]
This is Done in light of KSTAT 2.
