### ISSUE TITLE
Add a Scaffolding/Boilerplate for rapidly building a KalaStatic project

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#144]
@RobLoach and I 
Think http://khaos.io/ would be extremely useful for generating a 'kalastatic' that can be different things for different purposes and have it be more of a 'solution' than a 'boilerplate.'

**Comment by RobLoach** [comment]
Good candidate for https://github.com/kalamuna/kalastatic-cli

**Comment by madeofpeople** [comment]
:+1: :+1:

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/387
