### ISSUE TITLE
KalaStatic Presentation

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#146]
outline: https://docs.google.com/document/u/1/d/1bVMdzEVKiYWTANCnr89RtOW9d7YoXfsial_p-tJpmz0/edit?usp=drive_web

to become the deck:
https://docs.google.com/presentation/d/1lcs4FKu9SCNieHx7nkGHdBddnv1T0mKDMdqruozmywE/edit#slide=id.g46c3273d8_014

**Comment by RobLoach** [comment]
MultiDevs:

* [MDL Blog demo](http://mdl-blog-kalastatic.at.kalamuna.com/) from [kalastatic-cli mdl-blog](https://github.com/kalamuna/kalastatic-cli/tree/master/examples/mdl-blog)
* [Prismic demo](http://prismic-kalastatic.at.kalamuna.com/) from [the prismic branch](https://github.com/kalamuna/kalastatic/pull/130)

**Comment by andrewmallis** [comment]
@RobLoach are the branches on this repo committing via Travis to these environments?

I do not have access to the pantheon environments.

**Comment by RobLoach** [comment]
MDL blog is on Kalastatic Pantheon Multidev.... the source is on kalastic-cli.

**Comment by RobLoach** [comment]
you should have access on panth..
 Mallis@, right?

**Comment by andrewmallis** [comment]
confirmed. all is good.
