### ISSUE TITLE
hide code displaying on font-awesome page

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#148]
markup is printing edge to edge. doesn't look so hot. Let's hide it completely and default instead to the fontawesome docs:

### QA
http://localhost:8000/styleguide/section-6.html
http://test-kalastatic.at.kalamuna.com/styleguide/section-6.html

**Comment by andrewmallis** [comment]
don't see this on master or in a pull request, this is what needs to go away:

<img width="578" alt="style_guide" src="https://cloud.githubusercontent.com/assets/249362/8753836/e2e5d850-2c8c-11e5-9ca4-dfcb98ba076d.png">

**Comment by madeofpeople** [comment]
this is part of the kss template. and im not sure it can be selectively destroyed per page.

@robloach?

**Comment by RobLoach** [comment]
@thiago What are your thoughts on just providing the minimal Font Awesome docs, with links out to the official sources?

We could also hide it in the template itself with CSS.

**Comment by andrewmallis** [comment]
@RobLoach – I still see the code chunk at
http://test-kalastatic.at.kalamuna.com/styleguide/section-6.html
