### ISSUE TITLE
update about page with relevant content

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#150]
http://localhost:8000/about/

has pinnacle residue. reconsider

**Comment by andrewmallis** [comment]
let's point our CTAs to some wiki spaces, add some paragraphs of text, and an image or 2.

**Comment by andrewmallis** [comment]
Thiago's new homepage is cool. But so is Josh's content. Let's relocate this to the about page. @RobLoach will do this, then re-assign to @soniktrooth please.

**Comment by RobLoach** [comment]
-title: Who needs a CMS?		+title: Kalastatic
-subTitle: Kalastatic brings unprecedented levels of synergy to ensure dynamic convergence and top-line ROI for your static websites.		
 pageSlug: homepage		 pageSlug: homepage
 include:		 include:
   included: asection/asection		   included: asection/asection
 		 
 ---		 ---
-###Features		+A static site framework for quickly and effectively prototyping responsive sites, developing styleguides and designing in-browser.
-* [Metalsmith static](http://www.metalsmith.io/) site generator		
-* [Swig](https://paularmstrong.github.io/swig/) template engine		
-* [SASS](http://sass-lang.com/) CSS pre-processor		
-* [KSS](http://warpspire.com/kss/) CSS Documentation and Styleguide		
-* [Grunt](http://http//gruntjs.com/) for automating tasks		
 		 
-For moare information visit us on [Github](https://github.com/kalamuna/kalastatic) and check out the [wiki](https://github.com/kalamuna/kalastatic/wiki).

**Comment by madeofpeople** [comment]
So "Who needs a CMS?" 
Is clever placeholder copy Mr. Walker wrote.

But
a. We do.
b. It implies we're building this with the use-case of finished websites in mind.

Is that the message we want to convey?

@soniktrooth @andrewmallis @RobLoach

**Comment by andrewmallis** [comment]
good point @madeofpeople - edits welcome
