### ISSUE TITLE
Add links for actual news pages

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#151]
/news/collections/news/news-item-1 from /news/ is a 404. We should have actual news pages.

### QA
1. Visit /news/
2. clicking on an article should bring you to the news page.

**Comment by soniktrooth** [comment]
@madeofpeople is this just a matter of using permalinks?

**Comment by soniktrooth** [comment]
I had a bit of a look at this one and I could use some hints from @madeofpeople or @RobLoach as to how we can use the teaser template when we're on news collection page and the article template when it's a single news item page.

**Comment by RobLoach** [comment]
![http://i.qkme.me/3u8ekr.jpg](http://i.qkme.me/3u8ekr.jpg)

**Comment by madeofpeople** [comment]
Did we loose teasers in the main news page?

**Comment by soniktrooth** [comment]
@madeofpeople we didn't when I pushed it up. Thanks Ray (@RobLoach) for the vote of confidence.

**Comment by soniktrooth** [comment]
I just built the latest version and news teasers are fine for me @madeofpeople

**Comment by madeofpeople** [comment]
Yup the latest greatest is up there.
