### ISSUE TITLE
Style guide sidebar nav overflow

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#152]
Particularly evident on the components page. When the sidebar nav is long and the window is short it remains hidden and isn't scrollable. 

Possibly fix the height and overflow scroll, tighten up padding and head space in side bar.

**Comment by andrewmallis** [comment]
@madeofpeople has pointed us to http://tympanus.net/Blueprints/SlidePushMenus/

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap

Since it's bootstrap, there are likely some push menus that leverage the bootstrap components.

**Comment by madeofpeople** [comment]
I mean, it's just a fixed position element with some scss transitions on class change (little bit of classname toggling via js).

**Comment by thiagodemellobueno** [comment]
This one is actually fixed in the latest greatest, I created a new project here:
Which we should bring into kstatic 2 when we're a bit further along.
https://github.com/kalamuna/kalakss-template

**Comment by RobLoach** [comment]
As Thiago mentioned, this is fixed in http://sprint-dent.at.kalamuna.com/kalastatic/prototype/styleguide/section-custom.html ... This will be fixed inadvertently through https://github.com/kalamuna/kalastatic/issues/362 .

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/362
