### ISSUE TITLE
badges unstyled

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#154]
![style_guide](https://cloud.githubusercontent.com/assets/249362/8682344/5b85b17c-2a21-11e5-96cc-4565c2a1c032.png)

http://localhost:8000/styleguide/section-2.html#2.10

**Comment by madeofpeople** [comment]
just commented out in _boostrap_custom.scss 
I guess as default we should have a boostrap_custom, but have it be the full set, then folks can customize.

**Comment by andrewmallis** [comment]
:+1: to the defaults by default, and customizations as custom

**Comment by RobLoach** [comment]
Merged.

**Comment by andrewmallis** [comment]
:+1:
