### ISSUE TITLE
Nav issues: Whats kalastatic, whats a prototype, whats a styleguide, how do they relate?

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#156]
The organic growth of this project has lead to some shoehorning and confusion in the nav space. 

Why would the prototype have the styleguide in the nav?
How does one get to the styleguide if it's not in the nav?

**Comment by madeofpeople** [comment]
So when building locally, maybe kalastatic is an interface, an app.... 
The prototype and styleguide are things in it.

Here are some ideas that I sketched down during our discussion:

![a](https://cloud.githubusercontent.com/assets/79221/8682978/ecaaa7ea-2a3d-11e5-903f-284a8d165b68.png)
![b](https://cloud.githubusercontent.com/assets/79221/8682981/f43f36e2-2a3d-11e5-9ebf-f61230293a19.png)
![c](https://cloud.githubusercontent.com/assets/79221/8682982/f4418b36-2a3d-11e5-922d-1dbf6fe644f5.png)
![d](https://cloud.githubusercontent.com/assets/79221/8682980/f43ee14c-2a3d-11e5-9c49-c91bb706902c.png)

**Comment by madeofpeople** [comment]
Posting this, which I think @soniktrooth originally shared on slack.
http://rizzo.lonelyplanet.com/styleguide/ui-components/

**Comment by thiagodemellobueno** [comment]
The prototype / styleguide question is normally answered by, "prototypes are standalone components", prototyping is "those components in some specific context" ... 

Helps test edge cases, how things work in the different regions they might appear, answers "what happens when there are 3", etc.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kstat-kss-builder

**Comment by andrewmallis** [comment]
we have a new model with [kstatbuilder](https://github.com/kalamuna/kstat-kss-builder), and can display the nav in a stand-alone view thanks to KSS-3
