### ISSUE TITLE
Fix multi source KSS situation.

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#16]
```
{
  "source": "styleguide",
  "destination": "build/styleguide",
  "template": "node_modules/kss-bootstrap/bootstrap",
  "css": "build/styleguide.css"
}
```
Currently the source key points to "styleguide" as opposed to say "src/styles/"
Which takes the bootstrap kss nicely, but in fact leaves out all KSS documentation in the project itself.

is it possible that source be an array or sources?

@RobLoach, thoughts?

**Comment by madeofpeople** [comment]
Sadly it looks like 'multiple --srouce flags' in the json won't do it (tried).
So maybe we move away from the json config, and set up a scripts entry with all the options we want in package.json.

@RobLoach  thoughts?

**Comment by madeofpeople** [comment]
Self assigning this, need it today.
Working on branch kssmultisrc

**Comment by madeofpeople** [comment]
Oh, i see @RobLoach had fixed this using the symbolic link... so this was a bit of a non-issue.

Keeping this open though,  and pull-requesting, since I applied the fix above in the kssmultisrc branch.
There's also placeholder base stye documentation there that we should merge in anyhow.

**Comment by andrewmallis** [comment]
This issue has a distinct odor of genius.
