### ISSUE TITLE
Issue on responsive "Team"

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#162]
![screen shot 2015-07-16 at 11 45 34 am](https://cloud.githubusercontent.com/assets/79221/8727928/68536c92-2bb0-11e5-8692-bc1f304db375.png)

**Comment by madeofpeople** [comment]
We could. Make the excerpts the same length (a bit of a cheat but oh well).
Make this more an image name with modal bio (i can replicate kalacom here easily and genericky)
Or we can do some masonry, which is pretty simple really. Or matcheights (if were too scared to masonry)

**Comment by thiagodemellobueno** [comment]
This issue is relatively incompatible with our 2.0 objectives.
We're doing away with "kalastatic baselines with kalastatic site"
