### ISSUE TITLE
automate Travis build push Pantheon

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#165]
The build at
https://travis-ci.org/kalamuna/kalastatic
is ok, but does not push to pantheon:

```
Generation completed successfully!

The command "npm test" exited with 0.

$ echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
$ git config --global user.name $GIT_NAME
$ git config --global user.email $GIT_EMAIL
$ if [[ $TRAVIS_PULL_REQUEST != 'false' || $TRAVIS_BRANCH == "master" ]] && [ $TRAVIS_REPO_SLUG == $GH_REPO ]; then npm run deploy; fi
/home/travis/build.sh: line 41: [: kalamuna/kalastatic: unary operator expected
```
The Pantheon dashboard
for dev: https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#dev/code
and prismic: https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#prismic
don't show any pending commits

### QA

https://github.com/kalamuna/kalastatic/issues/238

**Comment by andrewmallis** [comment]
initially mentioned on #94, but seems to be across the board.

URGENT!
:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by RobLoach** [comment]
We never set up the public repository deployments, It works for when you're on a private repository, but for public, it requires a few more steps.

**Comment by andrewmallis** [comment]
@RobLoach should we discuss the complications in planning, or can you shed some light here?

**Comment by andrewmallis** [comment]
see #196

**Comment by andrewmallis** [comment]
@RobLoach here is some maybe helpful info
https://github.com/pantheon-systems/travis-scripts
https://github.com/pantheon-systems/circle-scripts

**Comment by RobLoach** [comment]
This is deploying on `master` now.

**Comment by RobLoach** [comment]
Bring latest master into `prismic2` branch, and then push to see if Pantheon is moving.

**Comment by RobLoach** [comment]
Same code as Greenbiz/kalamuna.com . It's acting differently though, I'll have another look.

**Comment by RobLoach** [comment]
https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#multidev/overview/git-branches

**Comment by soniktrooth** [comment]
This is done
