### ISSUE TITLE
Restructure things to use Atomic Components

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#167]
So we're looking to move to atomic.

- [x] Bring in the kala scss boilerplate that already sets up that structure
- [x] Since we're using metalsmith we may want to consider putting the partials markup and the corresponding scss and js into the same folder in source, then our components are self contained and metalsmith parses and aggregates all the stuff we need.
- [x] Convert current kalastatic source to follow the atomic principles.

**Comment by andrewmallis** [comment]
and of course we will store these in /sites/all/modules/ :wink:

**Comment by madeofpeople** [comment]
More like node_modules ;)

**Comment by soniktrooth** [comment]
https://github.com/kalamuna/sass-boilerplate

**Comment by andrewmallis** [comment]
worth thinking about how we connect this work to kalatheme, or hot_* features development so that our documentation and styleguide can stay in line

**Comment by madeofpeople** [comment]
Some possible fodder for this conversation here:
https://github.com/kalamuna/casperguide
