### ISSUE TITLE
hamburger nav renders as solid block of tofu

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#169]
<img width="441" alt="kalastatic_and_kalastatic_and_update_nav_ _kalamuna_kalastatic_52e38c2" src="https://cloud.githubusercontent.com/assets/249362/8760670/8c747c6c-2cf8-11e5-8d9c-dfc781a7f55a.png">

**Comment by andrewmallis** [comment]
less of a priority, but let's still take a look to ensure our baseline BS nav UX isn't overridden by our local styles, since it's a useful nav pattern in many sites

**Comment by soniktrooth** [comment]
I think someone sliced up the tofu and made burgers again.
