### ISSUE TITLE
"toggle nav" feature does not work

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#170]
<img width="662" alt="style_guide" src="https://cloud.githubusercontent.com/assets/249362/8760683/4c1893f0-2cf9-11e5-8cd1-a649f01f62c8.png">

**Comment by andrewmallis** [comment]
@RobLoach @madeofpeople - is this an issue for https://github.com/kalamuna/kss-bootstrap instead?

**Comment by madeofpeople** [comment]
very likely

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap/pull/19

**Comment by andrewmallis** [comment]
we'll discuss where to take this in #11

**Comment by andrewmallis** [comment]
@RobLoach 
http://dev-kalastatic.at.kalamuna.com/styleguide/section-2.html#2-8 removes the toggle nav, but my local build off the master branch at http://localhost:8000/styleguide/section-2.html still shows the toggle.
Thoughts?

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/191 and `npm install` should remove the toggle nav.

**Comment by andrewmallis** [comment]
I needed to delete node_modules before running npm install.
Thanks @madeofpeople !
