### ISSUE TITLE
provide simplified component architecture for tabs

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#172]
Tabs are a bit tricky. We've done things this way:

https://github.com/kalamuna/kalastatic/blob/9f03333643fcdc8a9a3a32f9ea3dcf6a9ad07dfe/templates/about.html

but it requires us writing everything in HTML and is messy.
It'd be great to pull in markdown files into the tabs.

purpose of this issue is to provide a documented example of tabs

**Comment by madeofpeople** [comment]
Is this a dupe of #136

**Comment by madeofpeople** [comment]
Didn't josh solve this with #136? 
Shall we close this?

**Comment by andrewmallis** [comment]
That was a duplicate issue. Neither has a resolution at this point. Moving to the icebox though as it isn't mission critical

**Comment by soniktrooth** [comment]
I have a working example in Progenity that can be generificated and rolled in.

**Comment by andrewmallis** [comment]
How do we generify and roll things in?
We no longer have a blueprint, but rather a framework.
This connects with the generator idea

**Comment by andrewmallis** [comment]
Components for a given project have the potential to be an npm or composer package
How we create libraries independent of projects for re-use requires some experimentation and thinking.
