### ISSUE TITLE
Breadcrumbs render characters

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#175]
<img width="884" alt="style_guide" src="https://cloud.githubusercontent.com/assets/249362/8762868/250fa2d0-2d53-11e5-97a4-63f6d577f972.png">

### QA
http://localhost:8000/styleguide/section-2.html#2.4

**Comment by RobLoach** [comment]
Bootstrap SASS: https://github.com/twbs/bootstrap-sass/issues/919
