### ISSUE TITLE
make directory structure more friendly

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#194]
https://gohugo.io/overview/source-directory/
has some nice patterns. Let's discuss.

we also have some conflicts with drupal, having a /templates directory

**Comment by andrewmallis** [comment]
layouts are better than templates semantically anyhow

**Comment by madeofpeople** [comment]
In a drupal context
```
THEME_ROOT
├─ Gruntfile.js // not necessarily part of kalastatic, builds css/js and moves them to compiled_theme_asset
├─ compiled_theme_assets // grunt moves js and scss here for drupal
└─ proto
    ├─ build // metalsmith builds here, node-connect serves from here
    |  └─ styleguide
    ├─ assets
    |  └─ src
    |     ├─ components // potentially holds 
    |     |  ├─ atoms
    |     |  ├─ molecules
    |     |  ├─ organisms
    |     |  └─ layouts 
    |     └─ styles
    |        ├─ base
    |        ├─ mixins
    |        └─ extendables
    └─ templates
```

**Comment by RobLoach** [comment]
Don't quite agree with having a irranious `assets` folder. The biggest take away from this is having the prototype system be a subfolder of the subtheme.

**Comment by andrewmallis** [comment]
#167 is related

**Comment by andrewmallis** [comment]
compiled_theme_assets > prototype_compiled ?
since we are compiling the prototype for theme. Current naming indicates we're compiling the theme.

**Comment by madeofpeople** [comment]
```
THEME_ROOT
├─ Gruntfile.js // not necessarily part of kalastatic, builds css/js and moves them to compiled_theme_asset
├─ compiled_theme_assets // grunt moves js and css here for drupal
└─ proto
    ├─ build // metalsmith builds here, node-connect serves from here
    |  └─ styleguide
    ├─ src
    |  ├─ components // potentially holds 
    |  |  ├─ atoms
    |  |  ├─ molecules
    |  |  ├─ organisms
    |  |  └─ layouts 
    |  ├─ styles
    |  |      ├─ base
    |  |      ├─ mixins
    |  |      └─ extendables
    |  └─ content // *.md files go here in their own structure.     
    └─ templates
```

**Comment by madeofpeople** [comment]
Big question how to get css and js things that drupal includes automagically compiled into static files and copied to the right location.

**Comment by andrewmallis** [comment]
let's rename proto > kalastatic !!

**Comment by madeofpeople** [comment]
THEME_ROOT
├─ README.md
├─ Gruntfile.js // not necessarily part of kalastatic, builds css/js and moves them to compiled_theme_asset
└─ kalastatic
    ├─ README.md
    ├─ build // metalsmith builds here, node-connect serves from here
    |  ├─ styleguide
    |  ├─ assets
    |  |  ├─ images
    |  |  ├─ fonts
    |  |  ├─ styles
    |  |  └─ vendor // this is where we redirect bower components
    |  └─ … // other proto buildout
    ├─ src
    |  ├─ components // potentially holds, do we need pages here
    |  |  ├─ atoms
    |  |  ├─ molecules
    |  |  ├─ organisms
    |  |  └─ layouts
    |  ├─ styles
    |  |  ├─ base
    |  |  ├─ mixins
    |  |  └─ extendables
    |  └─ content // *.md files go here in their own structure.     
    └─ templates // specific pages
       ├─ layouts // where html.html lives and such (better name for this?)
       └─ pages // ?

**Comment by andrewmallis** [comment]
floated: can `sites/all/themes/kalastatic` and symlink to `sites/all/themes/mytheme/proto` which might give us some flex to be both in and out.

**Comment by madeofpeople** [comment]
As far as drupal friendlyness goes, having a folder inside sites/all/themes that isn't a drupal theme sounds like a pretty bad idea.

**Comment by soniktrooth** [comment]
In a Druapl context KS probably is more akin to a library so maybe `sites/all/libraries`?

**Comment by madeofpeople** [comment]
Interesting.

Do paths get tricky there?
Or is pointing there from the theme.info kosher?

This will affect some of the ‘base_url’ stuff we’ve done? 

Eg. in the css paths relative to kstatic vs. path relative to drupal theme?

**Comment by madeofpeople** [comment]
See pr #201

**Comment by andrewmallis** [comment]
This is pretty good for now. We'll likely be doing another pass in the context of the CLI.
