### ISSUE TITLE
support node 4.x

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#199]
building on #111 

Given that https://nodejs.org/dist/ is not where people go to download node, and given that users of kalabox will most likely be on 4.x we should be sure to prioritize this issue for badcamp.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/200

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/203

**Comment by andrewmallis** [comment]
@soniktrooth || @madeofpeople are you using node 4?
I'd like confirmation this has passed QA by one more member, please.

**Comment by madeofpeople** [comment]
Indeed confirmed, and its been a few issue free weeks. Closing.
