### ISSUE TITLE
Document Deployment Methodology

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#2]
Here is a nice example for inspiration

https://gist.github.com/iamEAP/8855842

and a presentation: http://decks.eric.pe/pantheon-ci/#1 that is intro, but may help us inform documentation

**Comment by RobLoach** [comment]
:+1:

**Comment by RobLoach** [comment]
We could also grab things from package.json too.

**Comment by madeofpeople** [comment]
Our package.json is lacking a git repository field.
Also how would the workflow for building a kalastatic project work insofar as it needing a slightly modified package.json and yaml configs? 

Is this something we would set up a generator for?
Just documentation?

relates to some of the discussion here: #10 and #110

**Comment by andrewmallis** [comment]
Moving back to QA. it's not clear if/how this is done. Can you please inform/point to docs?

**Comment by RobLoach** [comment]
Document using grunt-build-control

https://github.com/kalamuna/kalastatic/blob/master/Gruntfile.js#L49

**Comment by andrewmallis** [comment]
@RobLoach to update build system m.o. now that we support multidev.
We also want to indicate how a user can deploy to their own Pantheon upstream target.

**Comment by andrewmallis** [comment]
```npm build deploy```

is supposed to work. Currently not.

```grunt deploy```

still works

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/wiki/Depolyment#deployment-from-local

`npm run deploy`

**Comment by andrewmallis** [comment]
I feel this could be clearer.

We should spell out a bit more what  ``npm run deploy`` actually does, and what kind of options can be passed here.
Can we describe usage for the github target at this point?
Can we elaborate some on our default configurations?

My assumption is that the cli will help much in helping clarify, because there is some circularity to the config right now with package.json

*Gruntfile.js*
```
    // The Build Control plugin:
    // https://www.npmjs.com/package/grunt-build-control
    buildcontrol: {
      options: {
        dir: 'build', // Which directory to deploy
        commit: true, // Only commit if code has changed
        push: true, // Push to remote
        message: 'Built %sourceName% from commit %sourceCommit% on branch %sourceBranch%'
      },
      // GitHub Pages target: https://pages.github.com
      github: {
        options: {
          remote: 'git@github.com:<%= pkg.extra.repo %>.git',
          branch: 'gh-pages'
        }
      },
      // The default deployment target, set in package.json.
      deploy: {
        options: {
          remote: '<%= pkg.extra.deploy %>',
          branch: '<%= pkg.extra.branch %>'
        }
      }
    }
  };
```

*package.json*
```
  "extra": {
    "repo": "organization/repo",
    "deploy": "ssh://our/pantheon/upstream/repository.git",
    "branch": "master"
  },
```

**Comment by RobLoach** [comment]
Updated some documentation in https://github.com/kalamuna/kalastatic/wiki/Depolyment#local-deployment . Most documentation is inline in Gruntfile.js, and on [BuildControl task](https://www.npmjs.com/package/grunt-build-control) itself. I've linked that in the docs.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/wiki/Depolyment#configuration

Add step by step for Travis deploy.

**Comment by RobLoach** [comment]
@madeofpeople Does this make sense to you?

https://github.com/kalamuna/kalastatic/wiki/Depolyment#automated-deployment

**Comment by madeofpeople** [comment]
The lucidity is inspiring!
:+1: :+1: :+1:

**Comment by madeofpeople** [comment]
Ready for deployment I'd say.

**Comment by andrewmallis** [comment]
we have some configurations in package.json under extra right now/ let's move everything configurable under config…

**Comment by andrewmallis** [comment]
updated README.md to express deployment

**Comment by andrewmallis** [comment]
normalized wiki page

**Comment by andrewmallis** [comment]
added a section on deploying to github pages too
