### ISSUE TITLE
Generic architecture for default state

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#20]
Discussions of what pages / nav kalastatic should have by default.

**Comment by andrewmallis** [comment]
proposing the following top level nav items:

- home
- about
- team
- news
- contact

**Comment by soniktrooth** [comment]
Sounds good—can we also flesh out what sort of example content we want on each? Probably want to cover as many bases as possible without too much redundacy. 

Home:
Some sort of hero treatment:
- jumbotron, call to action
- underneath 3 blocks, sub-call to action
eg http://getbootstrap.com/examples/jumbotron/

About
- a couple of paragraphs, a couple of images

Team
- card style layout with headshot and personnel info. ala current Kalamuna about page.

News
- list of teasers (with links to full page article? —not sure how necessary that is)
- ?side bar with archive dates implemented with scroll spy? Vague suggestion in effort to add some sort of griddy layouts and/or a bootstrap js component—not sure how necessary this is though.

Contact
- Form
- Map?

**Comment by andrewmallis** [comment]
don't think we want to promote the jumbotron + 3 blocks as our default – a simple splash page with a cover image could be better. @madeofpeople ?

There are also architectural components / design patterns we should consider and drop into the styleguide.

- CTA
- Hero
- Lede

We also tend to have these container type things which contain copy and or images and or columns

**Comment by andrewmallis** [comment]
opened #30 to provide a space to focus on homepage

**Comment by andrewmallis** [comment]
TODO: break out more specific issues besides #30 in the scope of 0.3

**Comment by andrewmallis** [comment]
ref #5 for the contact form

**Comment by andrewmallis** [comment]
This is actually done and done generically.
I think we're starting to get more specific in our next pass, which would invite another issue!
