### ISSUE TITLE
Create User Stories

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#206]
~~As a Kalamuna staff person, I want to see user stories about the goals of kalastatic integration with kalatheme, so that I can help inform their relevance in relation to my work.~~

As a Kalamuna staff person, I want to see user stories about the goals of kalastatic integration with kalatheme, so that I can help inform their relevance in relation to my work.

~~[Google doc](https://docs.google.com/document/d/1JjUWnrji7VSim-pjf2kFoYRSzP0J4FCKTYPVD5P7Qd4/edit#) for user stories~~

[Google Sheet](https://docs.google.com/a/kalamuna.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit?usp=sharing)

**Comment by andrewmallis** [comment]
The stories aren't just for me @RobLoach – how about:

As a Kalamuna staff person, I want to see user stories about the goals of kalastatic integration with kalatheme, so that I can help inform their relevance in relation to my work.

**Comment by soniktrooth** [comment]
As John Ouellet, I want to dominate all the things so that I can win. Trill.

**Comment by madeofpeople** [comment]
Last week I started a spreadsheet (what we've been using for other kala projects) 

https://docs.google.com/a/kalamuna.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit?usp=sharing

**Comment by RobLoach** [comment]
We have created User Stories, they will need clean up and prioritize via https://github.com/kalamuna/kalastatic/issues/218 . Feel free to push this to QA for Andrew Mallis.

**Comment by andrewmallis** [comment]
moving to #428
