### ISSUE TITLE
Prioritize User Stories

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#218]
We need to sift through and assign customer and business values to the user stories so it can serve as our north-star.

https://docs.google.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit#gid=0

**Comment by madeofpeople** [comment]
https://docs.google.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit#gid=0
