### ISSUE TITLE
Clean up User Stories

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#219]
https://docs.google.com/spreadsheets/d/1P0k9oiO5XFktye-0rr7YIuvi8IU1NeqvG1F1Ci-Gk6A/edit#gid=0

They need to be cleaned up and become readable....

> As a Solutions Architect	something about onboarding / evaluating

**Comment by madeofpeople** [comment]
Adding this link to #218  and closing this one.

**Comment by RobLoach** [comment]
:+1:
