### ISSUE TITLE
provide a sticky footer option

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#22]
likely a partial with a wrapper class applied to it
scss can likely still live in main footer styles
can we do this without js?

**Comment by madeofpeople** [comment]
Our aim to follow component conventions dictates that each component be self contained. So the css goes with it and there should be no 'main' footer style, and if there is, it shouldnt hold styling info for specific components.

Sticky footer can be done without JS.

Just 

```
position:fixed;
top: auto;
bottom: 0;
``
