### ISSUE TITLE
Clarify content exemplified in Examples

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#224]
They live in the Styleguide

- News
- Bootstrap Carousel

**Comment by madeofpeople** [comment]
Hmmm... I'm not sure they are the same thing.

A listing in situ. Example of how to put it in a proto.

One day we will split 'the site' from 'the source' but lets not do that tonight... please.

**Comment by soniktrooth** [comment]
This was always supposed to be fleshed out with examples of things that are bigger in scope than what would fit in the style guide. Granted we haven't had a chance to do that but I don't think we should nuke it.

**Comment by RobLoach** [comment]
Essentially, these are content examples, rather than examples of the components.

**Comment by madeofpeople** [comment]
Not so much as they are "how do you use kalastatic" where the style guide doesn't really provide that.
Example vs documentation (KSS)

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/commit/d6a75113be091b0663a2333d7d2f61c9c9dbd329

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/blob/d6a75113be091b0663a2333d7d2f61c9c9dbd329/src/content/examples.md
