### ISSUE TITLE
Create diagram for kstatic preso

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#230]

**Comment by madeofpeople** [comment]
![diagram](https://cloud.githubusercontent.com/assets/79221/10706854/f8776dd6-79b8-11e5-8632-c05bfccf0a52.png)

**Comment by andrewmallis** [comment]
Wonder if we should say prototype instead of kalastatic and CMS instead of Kalatheme.

Dev work to realize the prototype is in the theme layer, but also in the back end. And it might not be Drupal.

**Comment by andrewmallis** [comment]
Graphic is excellent.
I like how the client has 20/20 vision ;)

**Comment by madeofpeople** [comment]
Well, I'm open, and it could work either way, but kalastatic is itnegrating drupal workflows now so I thought it would be a nice tie in... still open to it.

**Comment by madeofpeople** [comment]
Updated diagram ![workflow](https://cloud.githubusercontent.com/assets/79221/10712613/fe2b2768-7a6c-11e5-8fcd-482548603e09.png)

**Comment by andrewmallis** [comment]
artwork lives in https://drive.google.com/drive/folders/0B6sweyW2_IqFdDJ0N2g2dzM0bzA for reference.
