### ISSUE TITLE
improve how we specify where kalastatic lives within drupal

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#235]
https://github.com/kalamuna/kalastatic_dot_module/blob/master/kalastatic.module#L155-L159

Currently we're hardcoding the path to kalastatic in the module for the purpose of it working in the test bed. I'd like a smarter way for the module to find it. 

What assumptions can we make? 
- Should the folder always be called `kalastatic`? 
- Is there a file with a specific name that we can search for that will guarantee we found the right folder? 
- Should we mandate that it always live within a theme so we can immediately limit our search to places where themes are found?
- Should we add a form where a user can provide the module with the location of KS? Thereby allowing it to live anywhere.

**Comment by RobLoach** [comment]
Discoverability at:
https://github.com/kalamuna/kalastatic_dot_module/blob/master/kalastatic.module#L250

Configuration text form in the config page is another option. Libraries expects things at `sites/all/libraries`, which may or may not be good. Perhaps integration with it, but not explicit dependency.

**Comment by soniktrooth** [comment]
Libraries module would only help us if kalastatic was living inside the module because  as part of hook_libraries_info we would still need to provide the path to where the 'library' is living. 

I'm going to go ahead and implement a form that saves a variable because this is the most flexible. Some smart file system and regex spelunking can be implemented at a later time.

**Comment by soniktrooth** [comment]
This is done with the following commit: 
https://github.com/kalamuna/kalastatic_dot_module/commit/191447605d8c2f547937a31bf97a6d712618b689

**Comment by RobLoach** [comment]
:+1:
