### ISSUE TITLE
Make styleguide base path work in a Drupal context

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#237]
In #202 we discovered that the styleguide's basepath isn't right when Kalastatic is living inside a Drupal theme.

There seems there's some Metalsmith complexity here and there was ideas and discussion had by @madeofpeople and @RobLoach. 

Please continue.

**Comment by RobLoach** [comment]
Fixed in KalaStatic https://github.com/kalamuna/kalastatic/pull/244 with relative paths.

Updating the test-site is a pain, I made progress in the `kalastatic-path` branch. Moving to a package model will fix that.

**Comment by soniktrooth** [comment]
#234 shows that this is complete.
