### ISSUE TITLE
Make the Styleguide Great Again

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#239]
### Goals:
- improve navigation
- more clearly delineate components from one another
## Realtes to
#289 Drastically improve Content of Styleguide landing page
#152 Style guide sidebar nav overflow
#156 Nav issues: Whats kalastatic, whats a prototype, whats a styleguide, how do they relate?
## Ideas
- provide ability to collapse code blocks (en masse or individually)

## TODO

- [ ] Port DENT Styleguide over to KSS3

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap

```
npm install
npm start
```

**Comment by andrewmallis** [comment]
our goals for this issue should be more clearly defined

**Comment by andrewmallis** [comment]
does this duplicate #295 ?

**Comment by soniktrooth** [comment]
c/o @cspin https://buffer.com/style-guide

**Comment by RobLoach** [comment]
I really like the Buffer one. Key improvements from it I see are:
- Nav on the left
- Floaty/sticky sidebar

**Comment by madeofpeople** [comment]
I've created this to ease the conversation along.

https://docs.google.com/a/kalamuna.com/document/d/159WYCYO8BZYYYCNQfrXT6ZWqgqUxWGLckuqpvroN214/edit?usp=sharing

**Comment by thiagodemellobueno** [comment]
![http://atomicdesign.bradfrost.com/images/content/styleguide-salesforce-colors.png]

**Comment by RobLoach** [comment]
- Implementation of ScrollSpy
- Clicking off the menu should close it

**Comment by RobLoach** [comment]
A lot of DENT would be good to bring forwards.

**Comment by RobLoach** [comment]
The Styleguide is great again...  https://github.com/kalamuna/kstat-kss-builder
