### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#24]
Should we add a search text field to the header? Somewhere else?

**Comment by RobLoach** [comment]
http://lunrjs.com/

**Comment by pirog** [comment]
ooooooo very sexy

**Comment by andrewmallis** [comment]
https://github.com/CMClay/metalsmith-lunr

A Metalsmith plugin that integrates the Lunr.js client side search engine.

**Comment by soniktrooth** [comment]
Whilst—yes,—it's sexy, is it really something will be needed? Does a prototype really need working search? OR is the goal that this would end up being used for real sites?

**Comment by andrewmallis** [comment]
Search shouldn't be a standard feature for a static, brochure site.
To filter news content, it could be a nice add-on.

**Comment by soniktrooth** [comment]
But for a prototype site that is going to end up being built out with a CMS it probably will be wanted.

**Comment by soniktrooth** [comment]
I added a dummy search bar in ad677258b9b928c6a6d290a84dc581cba95a3d71 Leaving this open as an enhancement for down the road.

**Comment by andrewmallis** [comment]
the primary purpose of the kalastatic site at the moment is to bust out sites that will remain static, or connect to a headless/api content feed. Search is an add on in that context.

**Comment by andrewmallis** [comment]
primary purpose revised to prioritize prototyping, so this probably a good thing to have

**Comment by andrewmallis** [comment]
a search component, or a couple patterns (!) is I guess what we're talking about

**Comment by andrewmallis** [comment]
let's try and keep the scope restricted to the visual styling of the element and not the whole response-interaction
