### ISSUE TITLE
Evaluate Prototyping Ecosystem

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#241]
look at what else is going on in the space

**goals:**  to give praise to the lineage, avoid reinventing the wheel, to draw inspiration

**Comment by RobLoach** [comment]
https://staticsitegenerators.net

**Comment by andrewmallis** [comment]
already in the wiki page at: https://github.com/kalamuna/kalastatic/wiki/Static-Site-and-Prototyping-Ecosystem :wink:

**Comment by thiagodemellobueno** [comment]
I have some real hands on experience with pattern lab now.
And would have lots to say about things if we picked up this conversation again.

**Comment by RobLoach** [comment]
@thiagodemellobueno Any outcomes? Thoughts? New improvements you'd like to see in KSTAT? New issues we should create?
