### ISSUE TITLE
access styleguide from more harmonious URLs

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#242]
right now we access the styleguide at
``sites/all/themes/kt_sub/kalastatic/build/styleguide``
which is not as intuitive, or site-independent as

``/styleguide``

Work to take place via menu callbacks at
https://github.com/kalamuna/kalastatic_dot_module

**Comment by soniktrooth** [comment]
@andrewmallis #234 already exists to address this issue.
