### ISSUE TITLE
Improve Drupal documentation

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#245]
Add documentation around how to integrate KalaStatic with Drupal.
1. Install kstat.module
2. Enable and set up settings
3. Configure Permissions
4. Layooting

When the prototype/styleguide exists alongside the Drupal theme, and is being committed as part of that repository, some modifications need be brought to the Drupal configuration itself: 

in .gitignore of the drupal stack, we need to add:

```
# KALASTATIC #
##############
node_modules
build
npm-debug.log
assets/vendor
```

and settings.php

```
// 7.21+ image hack for text-area images
// http://drupal.stackexchange.com/questions/63226/drupal-7-20-image-styles-return-a-url-with-access-denied
// this is likely required for the static prototype to render image files
$conf['image_allow_insecure_derivatives'] = TRUE;

```

This should be documented in the wiki.

**Comment by RobLoach** [comment]
1. README.md needs git
2. Check if node 0.12 works, check support for node 4/5?

**Comment by RobLoach** [comment]
Node 0.10/0.12 breaks. Node 4 and Node 5 work.

**Comment by soniktrooth** [comment]
https://github.com/kalamuna/kalastatic/wiki/Building-for-Drupal-Integration
https://github.com/kalamuna/kalastatic/wiki/Integrating-Kalastatic-with-Kalatheme

**Comment by soniktrooth** [comment]
Perms have defaults now: https://github.com/kalamuna/kalastatic_dot_module/commit/57dc73c5c4d4c281b6b4f1d1729a9aa73295a5f9

**Comment by RobLoach** [comment]
Combine the two wiki pages into one. Integrating KalaStatic with your Drupal theme. One Drupal Wiki Page To Rule Them All.

**Comment by andrewmallis** [comment]
https://github.com/kalamuna/kalastatic/wiki/Integrating-Kalastatic-with-Kalatheme
is specific to kalatheme; you'd need to be looking for this specifically.

https://github.com/kalamuna/kalastatic/wiki/Building-for-Drupal-Integration
Has some other info.

Neither of these pages are referenced on https://www.drupal.org/project/kalastatic
which where our Drupal audience will likely enter from.

**Comment by andrewmallis** [comment]
#51 is also related

**Comment by RobLoach** [comment]
These docs should likely live in kalastatic_dot_module: https://github.com/kalamuna/kalastatic_dot_module/pull/41

**Comment by RobLoach** [comment]
We did this for both D7 and D8. Closing.
