### ISSUE TITLE
KSS: Unknown argument: xdemo

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#246]
@RobLoach:
> On both node 0.12 and node 4, I got "Unknown argument: xdemo" when processing KSS.

### Steps to reproduce:
- download fresh Kalastatic
- run `npm install`
- run `npm start`
- loss

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap/commit/6beca267fe49139714e1058e1c2acc0f1954c499

**Comment by soniktrooth** [comment]
This is fixed
