### ISSUE TITLE
put kalastatic.module on d.o.

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#247]
https://github.com/kalamuna/kalastatic_dot_module is happy on github, but but we are seeking here to expose it, and the kalastatic project more prominently to the Drupal community.

## benefits: 
- visibility into the project spaces from another important vantage point
- googling "drupal prototyping" hopefully draws people in
- increase confidence in the community and client spaces that this is a legit thing

## TODO
create a sandbox project on d.o.
made @RobLoach @soniktrooth @andrewmallis maintainers
hook up the hubdrop integration so we can continue to jam on Github Inc
get us owners on the hubdrop repo too.

### QA 
https://www.drupal.org/project/kalastatic

**Comment by andrewmallis** [comment]
@soniktrooth would love to get this started sometime next week. SOWs for some upcoming client requirements dissuade our use of "custom code" and this approach makes things more community supported.

**Comment by soniktrooth** [comment]
Boomsauce
https://www.drupal.org/sandbox/sonictruth/2624634

**Comment by soniktrooth** [comment]
I've made you all maintainers

**Comment by RobLoach** [comment]
Commit all the things!

**Comment by andrewmallis** [comment]
Great work @soniktrooth, and thanks for the follow up issue @RobLoach.

I fee we should beef up the description an little bit on d.o. I was going to edit the description at https://www.drupal.org/sandbox/sonictruth/2624634, but instead updated the github README.md for a better audit trail and paricipation:

https://github.com/kalamuna/kalastatic_dot_module/blob/master/README.md

Please review, edit. From there, I would like to bring this into d.o. since it will help our application. I am not sure how we can best do that in a maintainable way. Perhaps @RobLoach has an idea.

**Comment by andrewmallis** [comment]
I wanted to change the demo URL from
http://kalastatic-kalatheme.at.kalamuna.com
to
http://kalastatic-kalatheme.at.kalamuna.com/kalastatic
which is the actual demo of the module, but now am getting access denied. Should we just set permissions on the site?

**Comment by soniktrooth** [comment]
This is great @andrewmallis I will add it to the sandbox page. 

The 404 would just be because the perms aren't set to allow anon users to see the prototype and/or styleguide.

**Comment by soniktrooth** [comment]
no, wait—http://kalastatic-kalatheme.at.kalamuna.com/kalastatic is the admin page. The link you want would be: http://kalastatic-kalatheme.at.kalamuna.com/kalastatic/prototype

I checked and anon has perms to view this.

**Comment by soniktrooth** [comment]
Do we want to allow anon to see the config page?

**Comment by soniktrooth** [comment]
Project page updated: https://www.drupal.org/sandbox/sonictruth/2624634

**Comment by soniktrooth** [comment]
ok, I've pushed the code up now — @RobLoach am I good to go ahead with the review process as per #252 ?

**Comment by andrewmallis** [comment]
The scope of this issue is looking decent.
Updated the project page to point to http://kalastatic-kalatheme.at.kalamuna.com/kalastatic/prototype

No anon view of the config page; they could break it all.

Posted a comment at https://www.drupal.org/coding-standards#comment-10625756
since https://www.drupal.org/coding-standards#naming pushes for README.txt but 
https://www.drupal.org/node/2181737 says .md is good.

I updated the README.txt again to be more in line with standards
https://github.com/kalamuna/kalastatic_dot_module/blob/master/README.md
though there is no obligation for this to be 1:1 with the project page so fine to leave that as is unless you think otherwise.

Can you please bring the README.md changes to d.o. @soniktrooth if you are fine with them?

**Comment by soniktrooth** [comment]
Ok, README.md is in and I adjusted the project page as well. I'm calling this one and we can move onto #252

**Comment by andrewmallis** [comment]
sounds good to me @soniktrooth
