### ISSUE TITLE
set no upstream for kalastatic on Pantheon

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#249]
I figured out how to do this.
option 1 is to create a new site
option 2 is blow away the history and re-import it. Given that our history is on github and the CI is all set up, that sounds like the better option.

**Comment by andrewmallis** [comment]
note: pay attention to the multidevs too:
![pantheon_dashboard](https://cloud.githubusercontent.com/assets/249362/11429312/31d5c456-942b-11e5-945c-a597c068b6ac.png)

**Comment by RobLoach** [comment]
We could likely blow the multidevs away, easily reproducible.

**Comment by andrewmallis** [comment]
Created 2 new wiki pages

[Changing upstreams on a Pantheon site after the fact](https://kalamuna.atlassian.net/wiki/display/KALA/Changing+upstreams+on+a+Pantheon+site+after+the+fact)

[Creating a Pantheon website with no defined upstream](https://kalamuna.atlassian.net/wiki/display/KALA/Creating+a+Pantheon+website+with+no+defined+upstream)

**Comment by thiagodemellobueno** [comment]
This one's rather old? Is it still relevant?

**Comment by RobLoach** [comment]
Quite old. Going to close it.
