### ISSUE TITLE
Character limit filter

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#25]
I think it would be handy—especially if this is being used to for prototyping Drupal sites—to be able to have a teaser type functionality. I already hinted at this by adding a teaser.html template but what it's missing is the ability to limit the characters in the contents variable.

I think this should be achieved fairly easily with a custom filter: http://paularmstrong.github.io/swig/docs/extending/

and 

Some regex awesome:
http://stackoverflow.com/questions/25817608/nodejs-swig-substring-or-limit-chars

**Comment by andrewmallis** [comment]
[metalsmith](http://www.metalsmith.io/) has some handy dandy plug-ins also:

https://github.com/kfranqueiro/metalsmith-more
https://github.com/blakeembrey/metalsmith-snippet

**Comment by soniktrooth** [comment]
Nice, I will check them out

**Comment by soniktrooth** [comment]
Those metalsmith plugins look like they do what we would want but I have no clue how to use them. I've ping @madeofpeople and hopefully he can help me.

**Comment by madeofpeople** [comment]
So i think the best bet here is to take a look at metalsmith-swig-helpers 
and create a filter: {{key|excerpt}}

Should be straightforward (specially if we can decently hardcode lengths).

I can handle it next week, or I can walk @soniktrooth through it later this week.

**Comment by soniktrooth** [comment]
I’d love the tutorial so I can do it myself next time. Still not feeling 100% on my knowledge of how metalsmith holds it all together.

**Comment by madeofpeople** [comment]
Well this step is getting a bit into node-modules.

But think of them as things that do one thing.

the metalsmith-swig-helpers just passes the instance of swig (the templating engine we’re using) certain bits.
http://paularmstrong.github.io/swig/docs/extending/

So we created the slug filter here:
https://github.com/madeofpeople/metalsmith-swig-helpers/blob/master/lib/index.js

Which is straightup Js.

For this we just need to do

```
swig.setFilter(‘excerpt', function(input,desiredLength){
	// default
	var desiredLength = desiredLength | 140;

	var summary = input.substr( 0, input.lastIndexOf( “ ",desiredLength ) ) + '...';
	return summary;
});

```
You would then do ```{{var|excerpt}}``` or ```{{var|excerpt|120}}```

Node is kind of magic.

I found this quite helpful in the past: http://www.sitepoint.com/understanding-module-exports-exports-node-js/




I doubt we would need multiple excerpt lengths per site very often.

**Comment by madeofpeople** [comment]
Added this to metalsmith-swig-helpers
```
{{varName|limit}} //defaults to 140 cause twitter
```
or
```
{{varName|limit|100}}
```

**Comment by madeofpeople** [comment]
See here https://github.com/madeofpeople/metalsmith-swig-helpers/blob/master/lib/index.js

**Comment by madeofpeople** [comment]
This is implemented, and working, chillin in QA

**Comment by soniktrooth** [comment]
Nice, I will test it out

**Comment by soniktrooth** [comment]
It no workey

**Comment by madeofpeople** [comment]
Bad documentation ... should be ```{{varName|limit(100)}}```

**Comment by madeofpeople** [comment]
![screen shot 2015-06-10 at 6 13 20 pm](https://cloud.githubusercontent.com/assets/79221/8095478/7acbb4fe-0f9c-11e5-8ffd-75b489bcbe4b.png)

**Comment by soniktrooth** [comment]
This is works for me. Good stuffz @madeofpeople.

**Comment by andrewmallis** [comment]
documentation is here: https://github.com/kalamuna/kalastatic/wiki/Filters

**Comment by madeofpeople** [comment]
:+1:
