### ISSUE TITLE
Implement CircleCI as an alternative to Travis

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#250]
https://circleci.com
Reports to be easier for managing keys.
Travis is trickier for public & private repos, requiring different configurations. Circle would store keys better.
- Testing
- Deployment
- Anything else they provide?

**Comment by RobLoach** [comment]
https://github.com/ucsf-dent/dentalcenter is on CIRCLE.

**Comment by RobLoach** [comment]
We could bring CircleCI support in here to act as a template for additional projects if they need them.

**Comment by thiagodemellobueno** [comment]
Is this more of an issue for say a "Kalamuna DevOps Practices" project? and less a kalastatic story?

I don't want to be ultra-orthodox, but we should probably separate "Kalastatic" from "How we implement kalastatic"

**Comment by RobLoach** [comment]
Agreed... While KalaStatic uses Travis for testing, the application of it can use CircleCI. We've made use of Circle and KSTAT many a times. Going to close this one.
