### ISSUE TITLE
Urge kalastatic.module through the review process on d.o.

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#252]
Once the module is :+1: and ready to become a full module on d.o, we should submit it to the module review process.

Assigned to Soniktrooth, as he holds the keys to the Kingdom, I mean, Sandbox.

https://www.drupal.org/sandbox/sonictruth/2624634

once the module is approved, we should fire up an issue to provide hubdrop integration

**Comment by RobLoach** [comment]
https://www.drupal.org/node/1068952

**Comment by soniktrooth** [comment]
Ran the module through http://pareview.sh/ and apparently we can not provide a LICENSE.txt, Drupal is supposed to do that. Is this problematic?

**Comment by soniktrooth** [comment]
Module review is up here: https://www.drupal.org/node/2636496

**Comment by soniktrooth** [comment]
GPL it is

**Comment by RobLoach** [comment]
https://www.drupal.org/node/2636496#comment-10952895

**Comment by soniktrooth** [comment]
@madeofpeople @andrewmallis @derekderaps if anyone wants to throw a positive comment on here that might help it along: https://www.drupal.org/node/2636496

**Comment by soniktrooth** [comment]
Project is approved and up: https://www.drupal.org/project/kalastatic

Still trying to get a release on the page.

**Comment by soniktrooth** [comment]
Ok, we have a downloadable 1.0—thanks @RobLoach. I didn't get the bit about needing to tag it for it to show up. All good now.

**Comment by RobLoach** [comment]
We're up! :+1: :dancers:

**Comment by soniktrooth** [comment]
@RobLoach I can't get a download link for the dev version to show up. You are a maintainer as well, any chance you can log in and see if you can get it working?
