### ISSUE TITLE
automate ingestion of resources from Drupal into the prototype

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#254]
In #243, we provided smoother deliver of the CSS and the JS via Drupal callbacks.
We're still cutting and pasting these resources into the prototype, but it would be advantageous to pull these in automatically.

We're looking for a metalsmith plug in at this point to pull the magic in.

**Comment by madeofpeople** [comment]
https://www.npmjs.com/package/metalsmith-kalastatic-dot-module
```test/index.js``` gives a nice simple functioning example.
Will mix up a PR in a bit.

**Comment by RobLoach** [comment]
Created some issues at https://github.com/kalamuna/metalsmith-kalastatic-dot-module . Not blocking the PR, or pushing this forwards though.
