### ISSUE TITLE
Breakpoint visualizer

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#262]
I recently did this on a project to help when developing which breakpoint I'm looking at. It's super handy and I think we could roll it in.

```
body {
  position: relative;

  &:before {
    @media(min-width: $screen-xs) {
      content: 'xs';
      width: 25px;
      height: 20px;
      padding: 3px;
      position: fixed;
      bottom: 0;
      left: 0;
      z-index: 999;
      background-color: #000;
      color: #fff;
      text-align: center;
      font-size: 12px;
      border-top-right-radius: 5px;
    }

    @media(min-width: $screen-sm) {
      content: 'sm';
    }

    @media(min-width: $screen-md) {
      content: 'md';
    }

    @media(min-width: $screen-lg) {
      content: 'lg';
    }
  }
}
```

**Comment by soniktrooth** [comment]
![breakpoint vizualizer](https://cloud.githubusercontent.com/assets/597617/12625025/c19a24ce-c4e6-11e5-9c2e-6ce84a61d386.gif)

**Comment by madeofpeople** [comment]
:100:

**Comment by madeofpeople** [comment]
I would break it out as a placeholder so it can easily be included for those that want it, but not be default (i thought i commented here?)... but otherwise this is super great.

**Comment by RobLoach** [comment]
Oh that's cool... Could we somehow check if we're on DEV in SASS to have this?

**Comment by andrewmallis** [comment]
Because the prototype is sharing its resources back to drupal, the breakpoint visualizer appears in this context too – not ideal for production sites.

We've established that everything going up to Pantheon will use the same build environment vars.

How can we only load this in the prototype context? npm start / test  but not deploy?

**Comment by soniktrooth** [comment]
We could add a class on the html or body tag in the prototype tpl and target that.

**Comment by thiagodemellobueno** [comment]
We should make this it's own component, rather thank include it in the main scss entry point.

**Comment by soniktrooth** [comment]
@thiagodemellobueno you are correct. And I believe the correct place for it is actually in https://github.com/kalamuna/sass-boilerplate

**Comment by soniktrooth** [comment]
@thiagodemellobueno  👆
