### ISSUE TITLE
provide ability to configure the pa11y reports

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#264]
Our reports at {{ /a11y/index.html}} are nice!
Per project, we may want to define the standards WCAG AA or AAA we want to test against. Configurability would be nice.

> The command-line tool can be configured with a JSON file as well as arguments. By default it will look for a pa11y.json file in the current directory, but you can change this with the --config flag:

```
pa11y --config ./path/to/config.json nature.com
```

see: https://github.com/nature/pa11y#configuration
## QA

https://github.com/kalamuna/kalastatic/wiki/Project-Configuration#pa11yjson

**Comment by RobLoach** [comment]
It's in the pa11y.json to select standard.

**Comment by andrewmallis** [comment]
Where does this live in our stack? I think we are currently using the command line arguments instead of the json file in our build, yes?

**Comment by RobLoach** [comment]
Add docs

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/wiki/Project-Configuration#pa11yjson

**Comment by madeofpeople** [comment]
@RobLoach  Good docs.
