### ISSUE TITLE
Make <base> easier to use

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#269]
It's all about that bass, but sometimes it isn't. If we were to remove this, would we break all the things? <base> looks like it only changes relative base path, rather than affecting styles/scripts.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap/issues/25

**Comment by RobLoach** [comment]
https://www.npmjs.com/package/metalsmith-prefixoid

**Comment by RobLoach** [comment]
Prefixoid won't do it, but `metalsmith-env` will: https://github.com/kalamuna/kalastatic/pull/271

**Comment by RobLoach** [comment]
Need to update the docs.

**Comment by andrewmallis** [comment]
things break @RobLoach 
could not reverse
https://github.com/kalamuna/kalastatic/pull/271
a :+1:  would have been good before merge.

http://localhost:8000/team/ doesn't load images
Then, from that page the menu links go to http://localhost:8000/team/about instead of http://localhost:8000/about

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/278

Now that we have `{{ basePath }}`, we need to use it. Was missing the new base.
