### ISSUE TITLE
main.html template

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#27]
Every time I've added a new page I've duplicated an existing template and renamed it so we've ended up with a few templates that all have the same markup, just different names:

```
{% extends 'html.html' %}

  {% block contents %}

  <main role="main">
    <article> 
      {{contents|safe}}
    </article>
  </main>

  {% endblock %}

```

This could just stem from the fact that I wasn't familiar enough with the previous implementation—but it seems a bit redundant. 

This relates to #23 where I'm questioning the use of the article tag as a wrapper for everything but my proposal is that we have a main.html to contain the markup above and then each page can use that as it's template and any page that needs any different wrapping markup can define a new one e.g. main-articles.html or similar.

**Comment by andrewmallis** [comment]
We should have a page.html template like pinnacle has for all generic pages.
The page-name.md can then reference that template.

We shouldn't need templates for every page, but will most likely for most.
Feeling we might need some group convo on this and brainstorming.

**Comment by madeofpeople** [comment]
Hellos. http://html5doctor.com/the-article-element/

**Comment by madeofpeople** [comment]
This is correct we should have article pages that follow the same patterns use "article.html", have the templates be pages, and defining what our base templates would be should be pretty straightforward and prioritized. 

Looks like in general we're looking towards using Atomic patterns:
http://bradfrost.com/blog/post/atomic-web-design/#templates
Atoms > Molecules > Organisms makes lots of sense, and building templates from organisms lends itself well to our approach so far.

Defining/Building layouts ought to be pretty straightforward, mostly a question of planning/documenting:
A couple of obvious ones
![two-col-content-first](https://cloud.githubusercontent.com/assets/79221/8193367/73763e4a-1442-11e5-8c66-f8156c35a94c.png)

![two-col-sidebar-first](https://cloud.githubusercontent.com/assets/79221/8193388/8949dd76-1442-11e5-9c52-53685dab638f.png)

![hero-three-touts](https://cloud.githubusercontent.com/assets/79221/8193501/33f456e8-1443-11e5-9ba4-d98f78c1dee9.png)

We'll want to try and name our layouts semantically so we're not just describing desktop arrangements, but naming use-cases.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/414
