### ISSUE TITLE
Discover which Absolute URL for Drupal Assets

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#270]
Have metalsmith_kalastatic package self-discover which Drupal assets to use?

**Comment by andrewmallis** [comment]
maybe should be in https://github.com/kalamuna/metalsmith-kalastatic-dot-module

**Comment by RobLoach** [comment]
https://kalamuna.atlassian.net/browse/EECS-203
https://github.com/kalamuna/metalsmith-kalastatic-dot-module

**Comment by RobLoach** [comment]
This is on EECS now. We likely QAed it on EECS already.

**Comment by soniktrooth** [comment]
This is GTG
