### ISSUE TITLE
Have KSS and A11y out of watch task

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#279]
Watching shouldn't run KSS/a11y.
## QA
1. Read through https://github.com/kalamuna/kalastatic/blob/kstat-279/README.md#tasks
2. If :+1:, merge  https://github.com/kalamuna/kalastatic/pull/285

**Comment by andrewmallis** [comment]
we should update the docs to promote a local task that can be run once in a while.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/285
