### ISSUE TITLE
FontAwesome

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#28]
Add font awesome for exceptional iconic radness.

**Comment by andrewmallis** [comment]
we have this!
https://github.com/kalamuna/kalastatic/blob/master/bower.json

**Comment by soniktrooth** [comment]
Yes, but it wasn't being included. Should be now though via 2577712b45616e2180b58bcfc2709d70ec067e71

**Comment by soniktrooth** [comment]
Done
