### ISSUE TITLE
assess implications of template keys in collection frontmatter

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#283]
revise these pages:
https://github.com/kalamuna/kalastatic/wiki/Using-collections-to-create-page-content-blocks

https://github.com/kalamuna/kalastatic/wiki/Creating-a-listing-from-a-collection.

**Comment by madeofpeople** [comment]
Working for event and event nodes in eecs.
Not sure why earlier we were getting the inclusion of a full template in looped items earlier.
