### ISSUE TITLE
Add a CHANGELOG.md so that we know what's in upcoming releases

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#288]
## QA

https://github.com/kalamuna/kalastatic/pull/319
https://github.com/kalamuna/kalastatic/blob/a67148304f64c3097b2288826aaeea123c35bda2/CHANGELOG.md

**Comment by andrewmallis** [comment]
maybe related to #263?

**Comment by RobLoach** [comment]
Uses https://www.npmjs.com/package/build-changelog , but we may want to manually create these changelogs.

**Comment by andrewmallis** [comment]
hm… looking at
https://github.com/kalamuna/kalastatic/pull/305/files
the changelog feels awkward to me.

0.6.3
doesn't correspond to our actual changelog at all…
it includes our initial commit.
Are we going to keep this entry in our changelog?

Also we mostly get a rather repetitive list of merges
``Merge pull request #244 from kalamuna/237-kss-bootstrap``
which is not really super duper awesome.

While it's pretty awesome that we can provide an automated changelog, I am not really feeling this solution is currently ready for primetime.

**Comment by andrewmallis** [comment]
release notes can also be added to github tags…

**Comment by RobLoach** [comment]
Started adapting our changelog over to be maintained manually. Will require a bit of work to maintain, but the effort will mean we have a better understanding of what is in each release.

**Comment by andrewmallis** [comment]
How can one QA the manual changelog @RobLoach ?
Is there a PR or is this in master now?

**Comment by RobLoach** [comment]
Missed the link, thanks. https://github.com/kalamuna/kalastatic/pull/319
