### ISSUE TITLE
cannot fork kalastatic into the organization

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#29]
I thought we would be able to fork kalastatic to create actual sites within the Kalamuna github org.

That does not seem to be possible.
Even if I rename the project, it will not then let me transfer ownership to the org:

![options](https://cloud.githubusercontent.com/assets/249362/5690186/058ac4c6-982f-11e4-84d3-0908dce64b5a.png)

This is a problem, because client sites will likely be private, and the org level account is paid for and can do this for us.

One option I see is to transfer Kalastack ownership to my account, then fork it to kalamuna for visibility at https://github.com/kalamuna/kalastatic/ but that is super awkward.

Looking for some workflow help here.

### ref

https://help.github.com/articles/transferring-a-repository/

**Comment by pirog** [comment]
Why not just set a new upstream and push thus avoiding the github fork
situation ?

On Friday, January 9, 2015, Andrew_Mallis <notifications@github.com> wrote:

> I thought we would be able to fork kalastatic to create actual sites
> within the Kalamuna github org.
>
> That does not seem to be possible.
> Even if I rename the project, it will not then let me transfer ownership
> to the org:
>
> [image: options]
> <https://cloud.githubusercontent.com/assets/249362/5690186/058ac4c6-982f-11e4-84d3-0908dce64b5a.png>
>
> This is a problem, because client sites will likely be private, and the
> org level account is paid for and can do this for us.
>
> One option I see is to transfer Kalastack ownership to my account, then
> fork it to kalamuna for visibility at
> https://github.com/kalamuna/kalastatic/ but that is super awkward.
>
> Looking for some workflow help here.
> ref
>
> https://help.github.com/articles/transferring-a-repository/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/29>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
Indeed. This does resolve the issue, but we do lose the social ties in github.com, no?
The repo won't say it's a fork of kalastatic anymore, right?
Of course, we will know…

**Comment by pirog** [comment]
You lose the ties but I think it's a zero sum game between the ties and
transferability which makes sense since a github fork is basically like
setting another remote from the source repo.

You can still contrib back you just need to manually push branches around
instead of using the UI.

On Friday, January 9, 2015, Andrew_Mallis <notifications@github.com> wrote:

> Indeed. This does resolve the issue, but we do lose the social ties in
> github.com, no?
> The repo won't say it's a fork of kalastatic anymore, right?
> Of course, we will know…
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/29#issuecomment-69445613>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by RobLoach** [comment]
Interesting issue. Perhaps we think of it as a boilerplate project rather than a project that we'd fork each time. Use git remotes like pirog mentioned, or just copy/pasta each time, and then manually merge downstream/upstream changes.

**Comment by pirog** [comment]
+1 the loach

On Monday, January 12, 2015, Rob Loach <notifications@github.com> wrote:

> Interesting issue. Perhaps we think of it as a boilerplate project rather
> than a project that we'd fork each time. Use git remotes like pirog
> mentioned, or just copy/pasta each time, and then manually merge
> downstream/upstream changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/29#issuecomment-69600960>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
It’s a public repository so I guess no reason why we wouldn’t use it the same way any other person would—clone it and push it to a new repo.

**Comment by andrewmallis** [comment]
Would have been nice to be able to easily see how many forks of kalastatic are out there… We can maintain a list on a wiki page, and outline adding forked sites there as part of the process.

@soniktrooth – typically, most people fork a project and push to their fork. Clone, then setting multiple upstreams is a bit less common. We did something sorta like that for another project:  http://projects.occupy.net/projects/fga/wiki/developer_guide#Managing-the-Pantheongithub-relationship

I'd like to document our process here: https://github.com/kalamuna/kalastatic/wiki/Contributing

**Comment by andrewmallis** [comment]
Another thought here. 
We could promote forking to the client org repo. 
Ultimately, they will own the code…
This will keep the tie in github to the project fork.

Currently, we're paying to keep clients' code private…

**Comment by andrewmallis** [comment]
https://github.com/kalamuna/kalastatic-cli
