### ISSUE TITLE
metalsmith-sass causes build errors

### ISSUE THREAD

**Issue by derekderaps** [kalamuna/kalastatic#296]
E.g., 
https://circleci.com/gh/ucsf-dent/dentalcenter/35
```
Metalsmith · [metalsmith-sass] Error: ".modal .modal-dialog" failed to @extend "%easeOutQuad".
The selector "%easeOutQuad" was not found.
Use "@extend %easeOutQuad !optional" if the extend should be able to fail. -> /home/ubuntu/dentalcenter/sites/all/themes/dentc/kalastatic/src/components/molecules/modal/_modal.scss:37:5
```
https://travis-ci.com/kalamuna/eecs/jobs/38117757
```
Error: [metalsmith-sass] Error: "%navbar-default" failed to @extend ".clearfix".
The selector ".clearfix" was not found.
Use "@extend .clearfix !optional" if the extend should be able to fail. -> /home/travis/build/kalamuna/eecs/sites/all/themes/eecs/kalastatic/src/components/organisms/eecs_nav/_eecs_nav.scss:21
```

**Comment by andrewmallis** [comment]
Bug could be reproduced locally once node_modules was cleared out.
We suspect node-sass and are seeking to peg this to an earlier version.

**Comment by derekderaps** [comment]
https://github.com/kalamuna/kalastatic/pull/297

**Comment by RobLoach** [comment]
Pegging in metalsmith-sass: https://github.com/stevenschobert/metalsmith-sass/issues/38

**Comment by RobLoach** [comment]
Closing now. We have the hot fix against all kstat projects, and the real fix in KalaStatic, which will be brought in next round of kstat updates.
