### ISSUE TITLE
bash variable

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#3]
My bash foo is weak. Can someone check what I've done with moving the repo address in travis-ci.sh into a variable? Unsure if it's a @RobLoach thing or a @andrewmallis thing. I will update this with a line number when I've pushed the initial code up.

**Comment by soniktrooth** [comment]
Ok, line [47](https://github.com/kalamuna/kalastatic/blob/master/ci/travis-ci.sh#L47) is where I set up the var and [67](https://github.com/kalamuna/kalastatic/blob/master/ci/travis-ci.sh#L67) is where I used it.

I also noticed just now that the check for $TRAVIS_REPO_SLUG is looking for "kalamuna/pinnacle" on line [50](https://github.com/kalamuna/kalastatic/blob/master/ci/travis-ci.sh#L50). I guess that will need to be a variable that can be set per project too but I'm unsure how that would have to be as it relates to Travis of which my foo is also weak.

**Comment by pirog** [comment]
@soniktrooth, @RobLoach @andrewmallis just saw this magic in my inbox and thought i'd chime in... might be nice to just set up a "config" area above all the fu so whoever is setting things up can just edit that and not have to worry about the chaos of my likely poor bash. praps something like this

```bash
#!/bin/bash

##
# PROJECT SPECIFIC SETTINGS
##
KALA_REPO_URL="git@alltherepos.com:mysickrepo.git"
KALA_REPO_SLUG="pirog/sloth-nasty-6000"
KALA_REPO_BRANCH="master"
...
KALA_OTHER_VARIABLE_SETTING="HACKTHEPLANET"

COMMAND=$1
EXIT_VALUE=0

##
# SCRIPT COMMANDS
##
...
```

Just a suggestion though so feel free to do whatever you guys things is best!

**Comment by soniktrooth** [comment]
Thanks @pirog that's great. I will do this thing.

**Comment by pirog** [comment]
Holla holla!!

On Friday, January 2, 2015, soniktrooth <notifications@github.com> wrote:

> Thanks @pirog <https://github.com/pirog> that's great. I will do this
> thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/3#issuecomment-68544532>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by soniktrooth** [comment]
Looking all good—closing.
