### ISSUE TITLE
provide a generic homepage

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#30]
What do we want out of a homepage?

There will be a lot of variation here, but we can likely define a few start states, or homepage template variations.

We'll want to go with one by default.

**Comment by soniktrooth** [comment]
I like the idea of having a few options that represent common homepage layouts. I've already done a 'jumbotron + 3 blocks' one which doesn't have to be the default as per @andrewmallis comment on #20 but it's still a common pattern. Perhaps a blog like '8 col content + 4 col sidebar'? Should be easy to spin up a few more options, we just need to decide which one we want as default.

**Comment by andrewmallis** [comment]
@madeofpeople is perhaps our approach to Pinnacle homepage a good default?

**Comment by madeofpeople** [comment]
@andrewmallis perhaps we should do more of a 

+---------------------------+
| Jumbotron                |
+---------------------------+
{{Contents}}
+------+ +------+ +------+
Title       Title      Title
Link       Link      Link
Blurb     Blurb     Blurb
+------+ +------+ +------+

**Comment by soniktrooth** [comment]
@madeofpeople I already did something similar to that but @andrewmallis wasn't that keen on making it the default. Other ideas? What was the Pinnacle layout @andrewmallis was referring to?

**Comment by madeofpeople** [comment]
That's

```
LARGE HEADLINE
----------   ----------
 Link        Link
 Title        Title
 Blurb      Blurb
----------   ----------
-----------------------
Link Title 
Blurb
-----------------------
```

but I'm not sure its a fine example of much.

**Comment by andrewmallis** [comment]
Do we really want people to clone and build kalastatic, hit the homepage and see something like http://getbootstrap.com/examples/jumbotron ?

I am guessing not. We are also highly unlikely to ever do such a homepage.

I would like to see our start state should be more genuine and punchy. A single full screen image with a headline and blurb would suffice.

We can employ the jumbotron + section/blurb pattern and still achieve this. Like: http://paulvanoijen.com/

So, I don't want to be a blocker in how we get there, but I do want to make clear that our outcome should feel bold.

Perhaps some kalastatic from this compendium of find gifs:
http://giphy.com/search/tv-static/5

Of course, these might trigger seizures. I can generate some custom static with kala brand colors via some previous, artful code experiments if that is desired.

**Comment by RobLoach** [comment]
> Perhaps some kalastatic from this compendium of find gifs:
http://giphy.com/search/tv-static/5

And now I have nightmares.

**Comment by andrewmallis** [comment]
![](http://i.giphy.com/aaa7yWzAsr2QU.gif)

**Comment by andrewmallis** [comment]
Let's use some static art on the homepage.

**Comment by soniktrooth** [comment]
![tumblr_nn0znm1wbe1ut8xpco1_500](https://cloud.githubusercontent.com/assets/597617/8135406/f988e33e-10eb-11e5-829f-4c37dd229708.gif)

**Comment by andrewmallis** [comment]
Hot. can blend into a background nicely too.
Happy to roll with this if it motivates you all.

**Comment by RobLoach** [comment]
I suggest this:

![Image](http://i.imgur.com/8NfYF3X.gif)

**Comment by andrewmallis** [comment]
:-1: on this as a proposal for the homepage
:+1: if this is the measure of your enthusiasm @RobLoach

**Comment by RobLoach** [comment]
Perhaps brings some of the notes from https://github.com/kalamuna/kalastatic/wiki into the homepage?

**Comment by soniktrooth** [comment]
I mucked around with static bgs and images and it all came off a bit OTT but I think I found something a little more subtle. 
@RobLoach @madeofpeople suggest you pull in the homepage-content branch and have a look.

**Comment by reynoldsalec** [comment]
@soniktrooth just glanced at this out of curiosity, great to see a start-state coming together that'll show people the simplicity of the platform.

**Comment by RobLoach** [comment]
Moving to QA since the PR is in.

**Comment by madeofpeople** [comment]
I'm not sure this is 'good enough to close.'

We talked about using the eye instead of the mouth? Do to it's working nicely with a grey background (not a trapped image).

I don't think that 'sexy mouth' though cool should be how we represent ourselves or our work.
If I were a female developer, otherwise disposed to engage this project… I might get turned off and write it off as more brogramming.

And the way the header touched/overlaps the image leaves wanting.
 
We should engage this sort of thing a bit more systemically.

**Comment by andrewmallis** [comment]
I also thought had consensus on the eye in https://github.com/kalamuna/kalastatic/issues/30#issuecomment-111562083

Guess we are not seeing eye to eye and this is hand to mouth:

![kalastatic](https://cloud.githubusercontent.com/assets/249362/8655387/a1d50e0c-2945-11e5-9a5b-1870442a3d38.png)

echoing Thiago's statements.

**Comment by andrewmallis** [comment]
looks like dev was not up to date. Local has another approach
http://localhost:8000/

![kalastatic](https://cloud.githubusercontent.com/assets/249362/8656350/dd4c0f84-294b-11e5-9c24-ef4473a39543.png)

let's eval

**Comment by soniktrooth** [comment]
New home page looks great but the animation is extremely grating after a few seconds. Maybe we could have it play a few times then stop? I feel like it could be an accessibility issue too—think epilepsy.

**Comment by madeofpeople** [comment]
It's not fast enough for epilepsy. 

As for the looping. I don't think it's super grating, but I'm open to set it to 5 loops or something if group consensus is that thats best.

**Comment by madeofpeople** [comment]
So honestly I think the homepage isnt something people will be spending a lot of time on, theres 2 lines of text and then people will head elsewhere. I think the looping should stay. 

We should def move on from this issue and sure up things elsewhere. And revisit if it becomes a priority / necessary.

**Comment by andrewmallis** [comment]
Let's explore this in another issue.
Good concern, but we need to move ahead and a bit of shock and awe is probably ok for tomorrow.

**Comment by soniktrooth** [comment]
yeah all good—I wasn't suggesting we need to lock this down now.
