### ISSUE TITLE
Share markup between prototype + styleguide

### ISSUE THREAD

**Issue by derekderaps** [kalamuna/kalastatic#300]
The markup in the styleguide does not power the prototype. This means work in two places when markup is adjusted: (1) YAML frontmatter and SCSS comments for the styleguide, and (2) Swig templates for the prototype.

This issue may resolve itself if/when we switch from KSS to something else.

@madeofpeople proposed writing a script to strip the YAML front matter from SCSS, so that KSS doesn't choke on it.

**Comment by RobLoach** [comment]
Big :+1: 

John Albin has done a lot of work on this in [kss-node](https://github.com/kss-node/kss-node), and I believe there are a few issues that reference it in our backlog. KSS uses Handlebars for its styleguiding currently, and there was talk about adapting it to use Consolidate, which would let us use any template engine with it. That stuff happens in [Builder.js](https://github.com/kss-node/kss-node/blob/master/builder/handlebars/builder.js).

Switching to Twig.js would be a good step towards unifying it all.

**Comment by madeofpeople** [comment]
As rob mentioned (i thought this was documented in a ticket but i couldn't find it). Ksss-node now accepts "generator objects" that can take any templating language ... someone would have to put oen together (though I think theres something in the works with twig).

This would allow us to automate this a fair amount. 

The yaml stripping, was just so we can preprocess our css to be KSS ready (but then metalsmith sass craps out on the frontmatter since it's not valid sass)

**Comment by RobLoach** [comment]
Stuck an issue in for KSS-Bootstrap: https://github.com/kalamuna/kss-bootstrap/issues/40

**Comment by RobLoach** [comment]
Switch to Twig https://github.com/kalamuna/kalastatic/issues/92

**Comment by madeofpeople** [comment]
Here's the discussion over at KSS-node re: "Generator objects" (though may start calling them "builders" to avoid naming conflicts with E6) https://github.com/kss-node/kss-node/issues/229

**Comment by derekderaps** [comment]
https://github.com/PatternBuilder/
https://github.com/phase2/drupal-lab

**Comment by andrewmallis** [comment]
@RobLoach mentions that John Albin did a good demo of 
native twig + KSS in Drupal 8.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/306 will be the place for that implementation.

**Comment by derekderaps** [comment]
Agreed. Closing this one out in favor of working from #306... Feel free to re-open if you think it makes sense to keep this issue around.

**Comment by andrewmallis** [comment]
@derekderaps this is the epic that groups our other issues together. Perhaps you meant to close out #302 in favor of #306?

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/92 would give a good groundwork on this epic.

**Comment by derekderaps** [comment]
Whoops! Okay that works.

**Comment by thiagodemellobueno** [comment]
![](https://s3media.247sports.com/Uploads/Assets/121/232/1232121.gif)

**Comment by thiagodemellobueno** [comment]
As of progenity (and im sure HSA) we are ready here.
