### ISSUE TITLE
Demonstrate Layout code in the styleguide

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#301]
Layouts are a means by which we lay out components.
Components are defined in the styleguide via KSS.

But, what about when we want to document the layout markup?

On EECS, we were looking to communicate the layout markup so that it could be re-implemented in another system. These are some of the same design goals we have for components.

see https://kalamuna.atlassian.net/browse/EECS-275 for reference on the issue resolution

relates to #36 : split templates out into a dedicated project

**Comment by andrewmallis** [comment]
Layouts typically need HTML and body tags, so we can't exactly place them on the page like other elements. We'd be looking at some kind of iFramed approach, but even then our breakpoints wouldn't be super demonstrable.

Perhaps a page per layouts? We'd highlight regions with borders and perhaps enforce some min-height and placeholder text with region names?

Perhaps an index page that lists the layouts and provides a UI to see the mark-up – like the KSS styleguide but without the preview above?

**Comment by RobLoach** [comment]
```
<iframe srcdoc="">
```

**Comment by RobLoach** [comment]
@soniktrooth did this on EECS last week.

**Comment by RobLoach** [comment]
![layooting](https://cloud.githubusercontent.com/assets/25086/15419387/9aa628c6-1e33-11e6-8a50-bf7f687bdeeb.png)

Looks great! Layooting win.
