### ISSUE TITLE
KalaStatic_Dot_Module: 404 on CSS

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#308]
http://gbz3-47ks-greenbiz.pantheonsite.io/kalastatic/prototype/styleguide/public/kss.css

Look at what we did in EECS to fix this.

`3` also showed up once too.

**Comment by andrewmallis** [comment]
Here was the issue in part:
https://kalamuna.atlassian.net/browse/EECS-187

permissions to view the prototype for anonymous + logged in users need to be set.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/245 Add Docs around installing KSTAT with Drupal.
