### ISSUE TITLE
Component style options

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#309]
When styling a component there are often various options or incarnations that can affect the styling of said component. As it stands I usually just add multiple versions of the component in the styleguide to display these variations however this can get ugly and cumbersome. 

I would like to explore adding some JS to the styleguide and perhaps some conventions for the KSS to allow us to add 'variant' buttons above a component to allow a user to click and view the variants of a component. For the most part this would just involve adding/removing a class on the wrapper. The tricky part is going to be coming up with a way to pipe knowledge of the component and it's variations through to the JS from KSS.

Thoughts @RobLoach @thiagodemellobueno ?

**Comment by RobLoach** [comment]
![buttons](https://cloud.githubusercontent.com/assets/25086/16093236/0c34b6ee-3309-11e6-89a8-c22f72b2113c.png)

Rather then showing all buttons, show just one, and then let the user select which modifier class to use?

**Comment by andrewmallis** [comment]
@RobLoach – the value-add for us is more for site specific components vs kss-boostrap.

**Comment by RobLoach** [comment]
@andrewmallis Could you clarify? KSS-Bootstrap is what the site-specific components uses to build out the styles on the styleguide. What do you envision this user interface looking like?

**Comment by thiagodemellobueno** [comment]
I would consider this done... 
Kss handles some level of variation.
BEM gives us block-element--modifier syntax
And extends basically make this very possible.

Also the work in the styleguide incorporates the "variants" idea josh proposed above by taking the kss variants and putting them in a drawer (though we may want a modal).

**Comment by soniktrooth** [comment]
yeah, I think we can call this one.
