### ISSUE TITLE
Check out SC5 for extreme styleguiding

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#314]
https://github.com/SC5/sc5-styleguide

**Comment by RobLoach** [comment]
One of the features I really like from SC5 is the Expand to Fullscreen button on each component. So I made an issue in the KSS-node front:
http://bit.ly/1UdsfVo

Also asked the members of the SC5 project is they could overview some of the differences:
http://bit.ly/261pQIl

Aidan mentioned SC5 may not be able to process on straight up CSS, and targets SASS. We could investigate more.

**Comment by RobLoach** [comment]
SC5 is KSS2... We're on KSS3 now, which gives us the goods and awesomeness. To make the Styleguide EXTREME, use:
https://github.com/kalamuna/kstat-kss-builder
