### ISSUE TITLE
Livereload/browsersync when inside Drupal

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#317]
Browser sync reloads the page on save for us nicely when building the prototype but it doesn't work when we're inside drupal. Thoughts on how we can get this working @thiagodemellobueno @RobLoach ?

**Comment by RobLoach** [comment]
Which site you working with?

**Comment by soniktrooth** [comment]
All of them

**Comment by thiagodemellobueno** [comment]
This has been won no?
I think greenbiz implents this no?
We definitely got this to work somewhere in the past.

**Comment by soniktrooth** [comment]
We talked about this today and landed on two possible options: 

- BrowserSync from within Drupal
https://www.drupal.org/project/browsersync

or a LiveReload snippet as such: 
```/**
 * Integrate with LiveReload 2. See http://livereload.com.
 */
/*
function stark_2_preprocess_html(&$variables) {
  drupal_add_js((drupal_get_path('theme',$GLOBALS['theme'])).'/js/livereload-snippit.js',
    array('type' => 'file', 'scope' => 'header')
  );
}```

**Comment by soniktrooth** [comment]
@RobLoach I've tried the Browsersync Drupal module but I can't get it working. Maybe we need a separate gruntfile in the root to handle this or something? I don't really know what I'm doing so if you could check it out that would be great.

**Comment by thiagodemellobueno** [comment]
@soniktrooth I expect that you dont need the special snippet with the browsersync module, since it probably handles that itself.

What is the configuration for the module like? Do you specify which things to "listen to changes on?"

**Comment by thiagodemellobueno** [comment]
From the browsersync notes: 

"Please note that this module DOES NOT run Browsersync for you. You will still need to run it from the command line using one of the following methods:"

That said, it's possible that running npm start will be enough (but also possible that we'll need to think about paths).

**Comment by soniktrooth** [comment]
@thiagodemellobueno yes, the module adds the appropriate js for us. 

The module settings look like this: 
<img width="968" alt="screen shot 2016-09-09 at 8 28 07 am" src="https://cloud.githubusercontent.com/assets/597617/18392653/6dd74fbe-7667-11e6-80ec-40a6c22166bc.png">

I was running browsersync on the command line like normal but it just serves the prototype. I tried changing the base dir to point at the root but that doesn't seem to work either.

**Comment by soniktrooth** [comment]
Ok, I got it happening with the following: 

Instead of 
```
        server: {
          baseDir: "./build"
        },
```
replace with this
```
        files: ["./build"],
        proxy: "kalatheme.local",
```

It's slow to spin up initially—like about a minute—but after that it seems to work well.

**Comment by soniktrooth** [comment]
I'm going to add this to the docs and then we should be able to put this to bed unless @RobLoach has some ideas on how to make this better.

**Comment by soniktrooth** [comment]
I added docs here: https://github.com/kalamuna/kalastatic/wiki/Building-for-Drupal-Integration

**Comment by RobLoach** [comment]
Looks good, added a link to the BrowserSync Grunt docs too.

**Comment by andrewmallis** [comment]
Everyone seems happy with this. 
@RobLoach would like if you can give it a quick test.

**Comment by soniktrooth** [comment]
actually, I'm seeing some more issues with this on DENT. Please hold.

**Comment by soniktrooth** [comment]
Ok, updated docs with new infoz. Ready for your eyes @RobLoach
