### ISSUE TITLE
Bower failed to install

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#32]
I'm trying to set up the first 'fork' of this for a client project and I've run into some issues. Running `npm install` give me the following error: 

```
54893 info install kalastatic@
54894 info postinstall kalastatic@
54895 verbose unsafe-perm in lifecycle true
54896 info kalastatic@ Failed to exec postinstall script
54897 error kalastatic@ postinstall: `bower install`
54897 error Exit status 1
54898 error Failed at the kalastatic@ postinstall script.
54898 error This is most likely a problem with the kalastatic package,
54898 error not with npm itself.
54898 error Tell the author that this fails on your system:
54898 error     bower install
54898 error You can get their info via:
54898 error     npm owner ls kalastatic
54898 error There is likely additional logging output above.
54899 error System Darwin 14.0.0
54900 error command "node" "/usr/local/bin/npm" "install"
54901 error cwd /Users/soniktrooth/Sites/mtc
54902 error node -v v0.10.35
54903 error npm -v 1.4.28
54904 error code ELIFECYCLE
54905 verbose exit [ 1, true ]
```

Hopefully I'll get to the bottom of it but I just wanted to add this issue incase it pops up for someone else. I'll update when I work out what the issue is.

**Comment by soniktrooth** [comment]
Seems like Bower is down—annoying, but nice that it's not a problem with our code. The error from Bower was 
``
bower EINVRES       Request to https://bower.herokuapp.com/packages/fontawesome failed with 503
```

visiting that url gives me a 503—even bower.herokuapp.com is 503-ing

**Comment by andrewmallis** [comment]
that is strange because .bower.json source is defined as git://github.com/FortAwesome/Font-Awesome.git not heroku

**Comment by soniktrooth** [comment]
bower.herokuapp.com just came back up and now it's installing fine—no idea what the deal is.

**Comment by andrewmallis** [comment]
oh, I see the bower registry stuff now.

**Comment by soniktrooth** [comment]
Anomaly
