### ISSUE TITLE
provide an active menu state via class

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#33]
we're going roll in progress from
https://github.com/kalamuna/pinnacle/issues/86

**Comment by madeofpeople** [comment]
See #68

**Comment by andrewmallis** [comment]
I'm visiting
http://0.0.0.0:8000/news/
but see no active class there.

**Comment by madeofpeople** [comment]
See pr #93

**Comment by andrewmallis** [comment]
@kalamuna/thiago – should we apply this to footer menus as well?

**Comment by madeofpeople** [comment]
Apply to footer.
