### ISSUE TITLE
Implement EQ.js

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#331]

**Comment by thiagodemellobueno** [comment]
I got to use this in appcivist, and have to say, assuming some control of markup, it is easty, superior to media queries and quite performative.

**Comment by thiagodemellobueno** [comment]
Is this something we would want to ever "add by default"
or is this more of a "how we implement kalastatic in a given project"

**Comment by RobLoach** [comment]
Yeah, seems not really part of KSTAT, but could be used on a project.
