### ISSUE TITLE
I got 364 problems and Sass is all of them

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#334]
After https://github.com/kalamuna/kalastatic/pull/333 is merged we will have the linter reporting: 

`✖ 364 problems (0 errors, 364 warnings)`

We should fix these.

**Comment by soniktrooth** [comment]
https://github.com/kalamuna/kalastatic/pull/336 addresses this

**Comment by soniktrooth** [comment]
Apparently only 15 warnings left—all of which are legitimate.

**Comment by RobLoach** [comment]
Well done, you two. SASSLint FTW.
