### ISSUE TITLE
Sidebar nav does not link to components

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#337]
In the current styleguide we link to each section with the ID attribute like so:

http://test-kalastatic.at.kalamuna.com/styleguide/section-2.html#2-6

```
<h2 class="kss-title" id="2-6">
  <span class="kss-ref badge pull-right">2-6</span> Labels
</h2>
```

In the new model, the intended target has the correct attribute:

```
<h2 class="kss-title" id="custom-link-2-button">
  <span class="kss-ref badge pull-right">custom-link-2-button</span> Button
</h2>
```

However the URL uses a period instead of a hyphen in the URL
http://sprint-dent.at.kalamuna.com/kalastatic/prototype/styleguide/section-custom.html#custom.link-2-button
should instead be
http://sprint-dent.at.kalamuna.com/kalastatic/prototype/styleguide/section-custom.html#custom-link-2-button
### QA

click on a component on the side navigation, and the pages should scroll down to this component
TODO: QA link in the KSTAT project proper

**Comment by thiagodemellobueno** [comment]
I can solve this one. 
It's a preventDefault() issue.
Rocking #330 should fix this one automagically

**Comment by thiagodemellobueno** [comment]
Also we kind of have that functionality with copy pasting links... 
we just need to make sure we update the hash.

http://sprint-dent.pantheonsite.io/kalastatic/prototype/styleguide/section-custom.html#custom-copyblock

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/issues/362
