### ISSUE TITLE
Allow Extended Filters to KalaStatic

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#340]
metalsmith-kalastatic-twig-filters exports it's Twig instance so that it can be passed into modules that might benefit from it's bounty.

It would be simple to alter jstransformer-twig to optionally accept a Twig (an extended one) instance to use. But kalastatic2 relies on metalsmith-jstransformer rather than calling jstransformer-twig 

(example untested code)

```
'use strict';

exports.name = 'twig'
exports.outputFormat = 'html'

module.exports = function(twigInstance) {
  module.exports.twig = twigInstance.twig || require('twig').twig
}

exports.compile = function (str, options) {
  // Construct the Twig options.
  options = options || {}
  options.data = str
  if ('filename' in options && !('path' in options)) {
    options.path = options.filename
  }

  // Build the template.
  var template = twig(options)

  // Use .bind() so that the template is "this" when rendering.
  return template.render.bind(template)
}
```

But since all the transformers go through metalsmith-jstransformer and get called in a for loop, it seems setting things up to allow for the handoff of twig instances somewhat complex, and involves altering multiple external modules.

I know this makes things very easily configurable (convention over configuration) but the tradeoff its not very flexible or extensible.

is it possible to have each jstransformer module be standalone?
What are some possible methods to deal with this?

I know populating key:value pairs holding modules to pass to each "named" transformer might work, but it seems like a lot of overhead / code / passing back and forth of stuff to achieve what is ultimately a pretty simple task (passing the extended twig instance for use by jstransformers-twig).

Thoughts?

**Comment by RobLoach** [comment]
Have Twig take `.options()` that would be passed over to the Twig instance. Had a quick hack at this last week, but plan to invest more time into it now. We'll need it to clean up the paths.

**Comment by RobLoach** [comment]
We've done this on HSA with `filters.metadata`, which extends Twig's Filter modal. Also created a [`twig-drupal`](https://github.com/kalamuna/twig-drupal) package which implements some of the Drupal Twig filters and functions, built from John Albin's KSS work.

I'll write some docs around this in KSTAT, and then assign to Josh Walker/Thiago for review.

**Comment by soniktrooth** [comment]
++ this is confirmed all happy in HSA. Assigning this over to @RobLoach to write up some docs on how it works.

**Comment by thiagodemellobueno** [comment]
++ 
I had peeked at this since it's already up in kstat 2 ... me likes.
