### ISSUE TITLE
Load metadata from JSON files matching content filenames

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#341]
so

```
button/
  _button.scss
  button.html
  button.js
  button.json
```

We could pass button.json into whatever is handling the twig to have access to those variables.

**Comment by RobLoach** [comment]
mypage.twig
mypage.json
mypage.twig would bring in the metadata from the JSON file.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/metalsmith-metadata-files is part of KSTAT3.
