### ISSUE TITLE
Highlight brand colors in the styleguide

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#342]
We should display the colors used on the site.
There may be some hierarchy needed.

TODO: augment issue with examples

**Comment by andrewmallis** [comment]
![ColorChips](http://atomicdesign.bradfrost.com/images/content/styleguide-salesforce-colors.png)

**Comment by RobLoach** [comment]
Those are some pretty colours.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/progenity.com/pull/178
