### ISSUE TITLE
Easily generate <picture> source sets based on Bootstrap breakpoints

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#349]
We need a way to easily generate `<picture>` source sets based on Bootstrap breakpoints. 

So I made a thing: 

https://soniktrooth.github.io/image-size-breakpoint-calculator/

This will be useful when making templates and allow us to make decisions about image sizes in prototyping phase rather than waiting until everything is already implemented on the Drupal. These will ultimately end up being Drupal Image Styles—which is the next step, but my thing solves this for KS.

Thoughts, questions, criticisms?

**Comment by RobLoach** [comment]
Pretty neat! Would be great to be able to use this as a library, maybe as a mixin, or a twig template, to generate picture elements. Added some issues here:
https://github.com/soniktrooth/image-size-breakpoint-calculator/issues

**Comment by thiagodemellobueno** [comment]
This would be a twig helper yesno?

**Comment by thiagodemellobueno** [comment]
Also how would a solution like #331 affect this? 

Would it?

Easier to ask "how much room is there for the picture" than "how big is the screen" ... no?

**Comment by thiagodemellobueno** [comment]
Isn't this acheived?

**Comment by soniktrooth** [comment]
Yeah, this is done.
