### ISSUE TITLE
Simplify Deployment Process

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#35]
Right now, we need Travis to run a build in order to deploy new changes. We should move this over to Grunt configuration so that:

1. You can do a deployment from your location machine
2. It's easy to change the desired deployment location via configuration variables
3. Use tested Grunt packages rather than straight up bash
4. Eases up the Travis deployment script

**Comment by pirog** [comment]
+1

this sounds great! def ping me when youve implemented... would love to check it out (read: steal and repurpose)

**Comment by andrewmallis** [comment]
**Initiative goals**

- able to push to github pages.
- increased transparency in what the CI id doing

**Comment by andrewmallis** [comment]
it was also noted that some configuration in how we handle permalinks would need to change to achieve this

**Comment by RobLoach** [comment]
We are now using [grunt-build-control](https://github.com/robwierzbowski/grunt-build-control) for deployments to Pantheon on GitHub Pages on a number of different projects.  I think what's missing is documentation.

1. Document generating GH_TOKEN secure keys within travis.yml itself
2. Document uploading SSH key to Travis
