### ISSUE TITLE
Clean URLs

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#358]
services.html
should be rendered to
services/index.html

**Comment by thiagodemellobueno** [comment]
do we want that?
don't we already have

/services 

why do we need /services/index.html

?

can you offer a use-case?

**Comment by thiagodemellobueno** [comment]
We used to use metalsmith-permalink for this very feature.

**Comment by RobLoach** [comment]
We'll need this for KCOM.

**Comment by soniktrooth** [comment]
YASSSSS

**Comment by soniktrooth** [comment]
@RobLoach How hard is this going to be?
