### ISSUE TITLE
split templates out into a dedicated project

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#36]
A very long term goal of providing more modularity and a smaller, more maintainable core would see us re-examining the contents and architecture of /src and /templates for cleanliness and a less kitchen-sink approach.

**Comment by madeofpeople** [comment]
As we move on some projects were doing IA and UX on, I would like to possibly create a set of components/tempaltes/theme for basic prototyping.

Borrowing from this:
https://drive.google.com/open?id=0B6sweyW2_IqFU1FaT2xldU1mTGM&authuser=1

and of course #31 

Something flexible we could use to make responsive unstyled mockups.

Also related: #84

**Comment by madeofpeople** [comment]
#178 makes this quite possible.

**Comment by RobLoach** [comment]
We've done this with:
- KSS Components for Bootstrap at https://github.com/kalamuna/kss-bootstrap
- KSS docs for Font Awesome at https://github.com/kalamuna/kss-font-awesome

Will remove the 2.0 milestone for now.
