### ISSUE TITLE
Bring the DENT Styleguide Goodness to KalaStatic/KSS3

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#362]
- [x] Port the DENT styleguide to KSS3
- [x] Stick it in its own repository
- [x] Bring it into KSTAT

**Comment by thiagodemellobueno** [comment]
Ready
https://github.com/kalamuna/kstat-kss-builder

**Comment by thiagodemellobueno** [comment]
@RobLoach close?
