### ISSUE TITLE
Create component command; kalastatic cc

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#364]
proposing

```kstat cc atoms/search-field```

generates

```
src
└── components
    └── atoms
        ├── _search-field.scss
        └── search-field.twig
        └── search-field.json
```

would save looooots of time in the 'flesh it all out' stages of a project
and further work towards kstat styleguide and proto serving as documentation for dev team and rapid delivery of spec.

**Comment by RobLoach** [comment]
++

**Comment by soniktrooth** [comment]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Although I think you meant: 

```
src
└── components
    └── atoms
        └──search-field
             └── _search-field.scss
             └── search-field.twig
             └── search-field.json
```

**Comment by thiagodemellobueno** [comment]
I do!

**Comment by RobLoach** [comment]
```
kalastatic create-component atoms/search-field
```

Would that work?

**Comment by soniktrooth** [comment]
@RobLoach that would be good. Could we alias it to `create` or something?

**Comment by thiagodemellobueno** [comment]
@RobLoach  @soniktrooth 
I think aliasing to cc is very nice.

**Comment by RobLoach** [comment]
```
kalastatic create --type=component atoms/search-field
```

`type` defaults to `component`.

**Comment by thiagodemellobueno** [comment]
What other types do you envision??
