### ISSUE TITLE
KSTAT2 - be able to set sass includePaths

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#369]
This could also read as:

Add a ```sass``` key to kalastatic.yaml that allows us to set sass compilation options.
(compressoin, nesting style, source maps, etc)

This is critical if kalastatic itself is agnostic about what sass is included.

**Comment by RobLoach** [comment]
This can be done with the YAML front-matter....

### main.scss
``` scss
---
includePaths:
  - some/directory
  - some/other/dir
---
.myclass {
  // Something.
}
```

Alternatively, https://github.com/kalamuna/kalastatic/issues/341 could also help in the JSON files...

```
button/
  _button.scss
  _button.json
  button.html
  button.js
  button.json
```
```
{
  "includePaths": [
    "some/other/path"
  ]
}
```

There's also a discussion about engine-specific options over at http://bit.ly/2gGHzwB too, which is a long-wanted feature I've wanted. Then you wouldn't need front-matter, and it would be in `kalastatic.yaml`.

**Comment by thiagodemellobueno** [comment]
Except that yams isn’t really part of a valid sass file, and there is already a spec for passing options to sass.
Why make a Rube Goldberg machine?

**Comment by RobLoach** [comment]
The engine option (number 3) is the solution you're looking for. The first two are just workarounds.... Allows having a sass key in kalastatic.yaml .

**Comment by thiagodemellobueno** [comment]
Could we discuss implementation solutions and their caveats ahead of implementation and inclusion into our production tools? 
Maybe the spec can be worked and refined? and multiple use cases considered? 

Sass files with yamls in the front matter will fail if run through most standard sass parsers, making the outcomes of using kalastatic  non portable (the assumption is that after stat they will go be used elsewehere).

Option 2 (#341) is a component specific discussion , and I'm not sure how it pertains to global configuration of the parser.

Can you elaborate on option 3? Which json file would it be where?

Why wouldn't we set it up so that our configuration file kalastatic.yaml passes the rendering engine variables in a way it expects? 

Imagine a new user coming to use kalastatic, wouldn't they assume that they have to update kalastatic.yaml to configure things?


Is it a question of convention over configuration?
Because it seems were going one step outside of that and creating conventions for unique configurations.

This just seems like such a roundabout way of saying "I want to use sass, and these are the ways I want the sass options set" 

It just seems that this approach took us from "easy and intuitive" in v1, to "occluded and requiring intimate knowledge" in v2....

**Comment by thiagodemellobueno** [comment]
It feels like Kstat 2 is becoming more and more an engineering driven development model, which doesn't take into account user cases, or the workflows of the users.

I know we're moving fast, but lets plan and design this thing, and validate our features ahead of implementation.

**Comment by RobLoach** [comment]
Can now add those paths in the kalastatic.yaml file...

```
pluginOpts:
  metalsmith-jstransformer:
    engineOptions:
      scss:
        includePaths: ['some/path']
```

The JSON Metadata solution may still be viable too. You're right that it is more component-specific rather than global, however. Let's see what we can come up with this week for that, and see which option works best.
