### ISSUE TITLE
Use Browsersync with kalastatic start

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#370]
Is there a specific reason?

Are we using PHP twig for things now?

Just seems like giving up a FAST technology to process potentially hundreds of files for a SLOWER technology would be something we do with great caution.
We got rid of ruby, but now are using PHP for our worflow server?

I know that half of this lives in Drupal, but REcoupling prototyping from implementation is something we need to be very cautious of.

**Comment by soniktrooth** [comment]
@RobLoach will know more but I think it was just a stop gap until we got browser stack back in.

**Comment by thiagodemellobueno** [comment]
:++:

Browsersync

**Comment by RobLoach** [comment]
Started on this over at https://github.com/kalamuna/kalastatic/pull/366 .
