### ISSUE TITLE
Things to steal for html.html 

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#38]
#37 got me thinking we might be missing some nice basics that could be stolen (graciously) from existing boilerplate type projects. e.g. [html5 boilerplate](https://html5boilerplate.com), [Google Web Starter Kit](https://developers.google.com/web/starter-kit/) etc.

**Comment by madeofpeople** [comment]
Very fine points.
Pulled in viewport meta... over at PR #71 

I'll add a ticket for favicons.
I agree that a bunch of best practices need to be included.

**Comment by andrewmallis** [comment]
Let's do a quick audit and create issues if need be, or close it
