### ISSUE TITLE
Component file naming conventions

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#395]
Previously we have used underscores exclusively when naming component files however Drupal has pretty strict requirements when it comes to template naming conventions. For ease of cross-pollination I'm going to suggest we adopt Drupal's conventions. This is less of an issue in D7 because we're calling the template ourselves with twigshim so it doesn't matter what it's called, however D8's template auto discovery won't work if we aren't using dashes. 

This is further complicated by the fact that we are using BEM when it comes to SASS extenables. I think we need to come up with a solid convention that works everywhere. 

Discuss.

**Comment by RobLoach** [comment]
:+1: .... I like use of dashes more than underscores. Any place in KSTAT that it's used? This more documentation issue linking to standard conventions we roll with?

**Comment by soniktrooth** [comment]
Yeah pretty much. I would like to standardize on BEM because there is logic behind it but I feel like that might not be compatible the the Durps. Will need some research.

**Comment by thiagodemellobueno** [comment]
I think BEM is dashes... so go feeder it.
But deeps combat of sho.

Is drupes conventions neatly summed up somewhere?

**Comment by derekderaps** [comment]
Just noting here for posterity: The way we solved this for now is to implement [`hook_theme_registry_alter()`](https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_theme_registry_alter/7.x) and change the template used.

**Comment by soniktrooth** [comment]
I don't think we're going to get this anytime soon. Drupal uses only dashes for template names, BEM allows for both dashes and underscores. Holding out hope for Drupal 9.
