### ISSUE TITLE
Migrate wiki to readthedocs

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#399]
A lot no longer applies.
We will use https://readthedocs.org
which will provide versions of documentation. This will, I feel be better since some things apply to both 1.x and our current version(s).

First step is to migrate what we have to the platform, then expand/re-organize

**Comment by andrewmallis** [comment]
We can also consider using https://readthedocs.org/
which will provide versions of documentation. This will, I feel be better since some things apply to both 1.x and our current version(s).

**Comment by soniktrooth** [comment]
Migration is done. 

- http://kalastatic.readthedocs.io/en/latest/ == master
- http://kalastatic.readthedocs.io/en/stable/ == latest version tag
- http://kalastatic.readthedocs.io/en/docs/ == docs branch

**Comment by andrewmallis** [comment]
@soniktrooth – I'd like to see the 1.x docs parked in a more clearly labelled space than `docs`.
We can cherry pick the docs stuff into our existing 1.x branch. This will let us easily remove the extra 2.x pages from that documentation if we want to, while moving ahead on the current 2x documentation in stable/latest.

What do we want to do with the new [docs-two-point-oh](http://kalastatic.readthedocs.io/en/docs-two-point-oh/) branch? It's awkwardly named. Should we use latest/stable?

@derekderaps also mentioned using tags.

@soniktrooth please get together with @RobLoach to tidy things up.
