### ISSUE TITLE
display colors in sections in the styleguide

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#404]
building on #342 we would like to group images into sections. Particularly useful when there are many colors.

Pattern lab is like so:

![pattern_lab](https://cloud.githubusercontent.com/assets/249362/22565396/d0086b80-e93c-11e6-9bda-c88850210ad1.png)

though we may want to look at more beautiful models.

**Comment by thiagodemellobueno** [comment]
Multiple color sections impleemnted https://github.com/kalamuna/kstat-kss-builder/pull/11
