### ISSUE TITLE
path and url functions for D8

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#411]
Drupal 8 implements `path()` and `url()` functions in twig for rendering internal and external links respectively. Kalastatic should implement these functions at least in a basic manner so we are able to use them in our templates and get the benefit on the Drupal side. In KSS it would be fine to just return a `#` because we just need links to look like links. In Metalsmith however we might want to get more complicated and look up the referenced route and try and construct a url to keep the prototype more 'life-like'. 

See the following article on use cases: https://chromatichq.com/blog/creating-links-within-twig-templates-using-path-and-url

**Comment by soniktrooth** [comment]
@RobLoach took care of this with grace and efficiency.

**Comment by RobLoach** [comment]
Added path to drupal-twig-filters and kss... We'll need to update KSS.
