### ISSUE TITLE
add code comments to js

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#42]
Looking at the existing js files, what things do and why they do them could be more obvious.

it's also been suggested that a /src/js/README.md would help explain when new files should be created.

existing code in 02.about.js seems pretty re-usable if further abstracted too. That's maybe another issue…

**Comment by madeofpeople** [comment]
I did one better, and documented the patterns in the js.

https://github.com/kalamuna/kalastatic/wiki/Javascript-Module-pattern.

@soniktrooth @RobLoach edits welcome.

**Comment by soniktrooth** [comment]
This is great @madeofpeople. I think this belongs in the kala wiki as well so we can standardise these things on all our sites. I fixed up the formatting on the code comments a bit just so they didn't scroll off the edge and a couple of typos.

**Comment by madeofpeople** [comment]
Thanks @soniktrooth I'll pop it in the wiki.

**Comment by madeofpeople** [comment]
https://kalamuna.atlassian.net/wiki/display/KALA/Javascript+Guidelines

**Comment by soniktrooth** [comment]
This is good.
