### ISSUE TITLE
support markdown for managing menus

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#43]
https://github.com/kalamuna/kalastatic/wiki/Adding-menu-items

shows how we do this in metalsmith.json but we'd like to support menu management in markdown files.

**Comment by madeofpeople** [comment]
Andrew, please elaborate on what "support menu management in markdown files." looks like?

**Comment by andrewmallis** [comment]
a markdown file for primary-nav.md could look something like:

- home | / | "the homepage"
- about | /about
-- "our-team" | /our-team | "our people rock"
- blog | "http://blog.mysite.com" | "visit the blog"

**Comment by madeofpeople** [comment]
Correction to your syntax... 
Links are as such.  [Link Label](http://url.com/ "Titleattribute")

I see how this keeps certain flows within the content-editor space.
But it also is starting to put non-content things, where content goes.

So a couple of things: 
1. We wont be able to add clases to these. 
2. We can, but then we're just editing html... which we should stay away from 

I can imagine cases that are not a main site nav, benefitting from this, though I think it's best solved differently. What do you think of having site-nav.yaml and leverage:
https://www.npmjs.com/package/metalsmith-metadata

**Comment by andrewmallis** [comment]
right. markdown link format in a .md is de mesure.
I guess what I pseudo-coded is more inline with a navigation-primary.yaml

Customizable classes per nav item seems like an edge case, but what adding the link label as a class as we are doing on kala.com seems like a good default.

You can see in http://dev-mtc1.at.kalamuna.com how management of nav links as content could be useful. We have a big footer and drop-downs on the primary nav.

**Comment by RobLoach** [comment]
Yeah, having this done with YAML might make it a bit more sane. That in conjuction with using some template ninjitsu would be wondermasterful.

**Comment by RobLoach** [comment]
Prerequisite: https://github.com/kalamuna/kalastatic/issues/47#issuecomment-75328709

**Comment by madeofpeople** [comment]
Should we close this?

**Comment by andrewmallis** [comment]
closing
