### ISSUE TITLE
Overview - Features

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#435]
## QA

https://github.com/kalamuna/kalastatic/blob/master/docs/index.md#kalastatic

**Comment by andrewmallis** [comment]
We had some nice features listed in the 1.x version of the docs. It would be nice to list things like this out early on. We need to outline differentiators from Patternlab and other solutions:

- Documentation
- Automated Deployments
- Development
- Easy installation, with minimal dependencies
- Automated download of Bootstrap and other dependencies
- Built in webserver
- Livereload - saving files reloads the browser
- Remote device access - load your local on a mobile device!
- The sytles produced by the prototype are immediately ingestible by the final site, no need for handoff and cross-maintenance.
- Design
- Produces documented component library
- Easy creation of extendable template variations with inheritance
- Output production ready styles
- Convenience Utilities
- cache busting
- deep linking (url fragments)
- character limit filters
- splits CSS files for IE compatibility

not saying all these need to stay, but these kinds of bullets are useful imho

**Comment by soniktrooth** [comment]
@andrewmallis I have a PR for you to look at: https://github.com/kalamuna/kalastatic/pull/490

**Comment by RobLoach** [comment]
Nice one.... We have a Features list. Open up a new issue if there's any further feedback on it.
