### ISSUE TITLE
Would saving in prose.io trigger the cli?

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#44]
This would be useful to get content-editors involved in the git-workflow.
Otherwise they would not have the ability to publish (this doesnt matter with the pantheon, since they probably wouldnt want to clear the caches there either... is there a way to automate that?)

Would we want them to work on master?
If not, how would they publish.
Is this more reason to migrate previewing to GHpages?

**Comment by RobLoach** [comment]
If it's pushed to master, then yes :+1: .

**Comment by andrewmallis** [comment]
see #10 too.

**Comment by andrewmallis** [comment]
#49 would need to happen if prose.io is the authoring platform

**Comment by andrewmallis** [comment]
let's update the documentation?

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/wiki/Depolyment
