### ISSUE TITLE
provide a carousel partial

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#45]
Ok, we all love carousels, right?

@soniktrooth has put together a nice partial for a default bootstrap carousel for MTC
https://github.com/kalamuna/mtc/blob/master/templates/partials/carousel.html
+
https://github.com/kalamuna/mtc/tree/master/src/collections/carousel

from that we'd likely want to break out the carousel styles from
[_homepage.scss](https://github.com/kalamuna/mtc/blob/c85b2ff40cceb15f0ab5b431c1e57135294cd87a/src/styles/layouts/_homepage.scss)
into a _bootstrap-carousel.scss

and perhaps renamespace our partial to boostrap-carousel.html so other implementations can co-exist in the stack.

**Comment by andrewmallis** [comment]
@madeofpeople if you have any thoughts, please let us know.
Of course there will be a pull request.

**Comment by madeofpeople** [comment]
I agree, with the naming convention.

**Comment by madeofpeople** [comment]
Run with it.

**Comment by soniktrooth** [comment]
This is done
