### ISSUE TITLE
Documentation 1.x README.md

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#469]
From https://github.com/kalamuna/kalastatic/issues/435#issuecomment-298793433 ... https://files.slack.com/files-pri/T024Y2MQC-F58J97VV4/download/kstat-index1.rtf

> Documentation
Automated Deployments
Development
Easy installation, with minimal dependencies
Automated download of Bootstrap and other dependencies
Built in webserver
Livereload - saving files reloads the browser
Remote device access - load your local on a mobile device!
The sytles produced by the prototype are immediately ingestible by the final site, no need for handoff and cross-maintenance.
Design
Produces documented component library
Easy creation of extendable template variations with inheritance
Output production ready styles
Convenience Utilities
cache busting
deep linking (url fragments)
character limit filters
splits CSS files for IE compatibility

**Comment by soniktrooth** [comment]
@RobLoach I'm not sure what is needed in this issue.
