### ISSUE TITLE
support global variables

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#47]
_config/globals.yaml

could provide us some boilerplate variables and arbitrary vars. 

Examples
```
copyright_year: 1999
twitter_name: @statamic
support_email: help@example.com
```

**Comment by andrewmallis** [comment]
@RobLoach – I take it swig does not support this?

**Comment by RobLoach** [comment]
Great idea... We should move all of this meta-data into a `.yml` file too:
https://github.com/kalamuna/kalastatic/blob/master/metalsmith.json#L3

**Comment by madeofpeople** [comment]
@andrewmallis right now anything in the metadata key IS a global variable, but having a globals.yml will be nice and accessible.

**Comment by andrewmallis** [comment]
I was just about to ping you on this. Good to know about the globals!
Maybe we should document this variable reality? Was looking in the wiki on where that could live. Perhaps we need a new page on Metalsmith?


Anyhow. Seems like there's some decent momentum to explore this.
Don't think this is a must have for 1.0, but would be real nice, and bring clarity to our key persona.

Going to keep this in the backlog, but assign to Rob for now inviting a pull request.

**Comment by madeofpeople** [comment]
I think a page on kalastatic rather than metalsmith is the way to go.
(With subpages of course),

**Comment by madeofpeople** [comment]
@andrewmallis it's been documented for some time here:
https://github.com/kalamuna/kalastatic/wiki/Looping-through-object-inside-metalsmith.json%5B%27metadata%27%5D/_edit

But im now editing the page for the config.yaml

**Comment by madeofpeople** [comment]
Resolved.
