### ISSUE TITLE
populate readthedocs stable with latest tag

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#470]
https://github.com/kalamuna/kalastatic/releases
let us know if we need to do something manual with releases to get docs in the future

## QA
http://kalastatic.readthedocs.io/en/stable/
should show docs

**Comment by soniktrooth** [comment]
A huh!I worked it out. It seems it didn't rebuild itself when the 3.2 release was rolled. Just manually rebuilt stable and it now is pointing at the correct commit. We will need to watch this next time a release is rolled.

**Comment by RobLoach** [comment]
http://kalastatic.readthedocs.io is working too. Nice one, Josh. :+1:
