### ISSUE TITLE
Documentation: kalastatic cc

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#480]
Add README.md and /docs stuff for create-command.

**Comment by soniktrooth** [comment]
@thiagodemellobueno Is there something somewhere for me to QA? or should this be in todo?

**Comment by RobLoach** [comment]
http://kalastatic.readthedocs.io/en/latest/2-Components/#create-component

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/506

**Comment by soniktrooth** [comment]
This is looking good now. I made a small change to fix a little layout issue: #510
