### ISSUE TITLE
JohnO Debrief

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#485]
@labboy0276  worked on some kalastatic stuff on a d8 site.

It wasn't a traditional paragraphs build, but he has some painpoints, and some improved-helping-with-things-code... 

we can learn a lot from our first non-core internal kstatic experience, and should do a little post-op discovery to see where we can make things better.

That's why this issue exists.

I'm assigning it to everybody.

**Comment by RobLoach** [comment]
Documentation.

**Comment by RobLoach** [comment]
- https://github.com/kalamuna/kalastatic/issues/491
- https://github.com/kalamuna/drupal-project/issues/28
- https://github.com/kalamuna/kalastatic/issues/492

**Comment by RobLoach** [comment]
Closing this, we have issues for each note.
