### ISSUE TITLE
clear pantheon caches on dev post-deployment

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#49]
If pantheon is our upstream target, it would be great to clear varnish caches there after kalacommitbot pushes. Clearing caches with drush will achieve this.

## QA
https://github.com/kalamuna/kalastatic/issues/304

**Comment by andrewmallis** [comment]
https://www.getpantheon.com/docs/articles/local/terminus-the-pantheon-command-line-interface/

shows us a couple extra things via terminus that'd be good form:

- [pantheon-site-wake](https://www.getpantheon.com/docs/articles/local/terminus-the-pantheon-command-line-interface/#pantheon-site-wake)
- [pantheon-site-environment-redis-clear](https://www.getpantheon.com/docs/articles/local/terminus-the-pantheon-command-line-interface/#pantheon-site-environment-redis-clear)

**Comment by RobLoach** [comment]
https://github.com/pantheon-systems/cli

**Comment by andrewmallis** [comment]
pushing back to 0.5 but let's prioritize, as this features is just as handy as live-reload and will save much grief

**Comment by andrewmallis** [comment]
related to #95 maybe

**Comment by RobLoach** [comment]
I believe Pantheon does this for us on a code sync. Just deployed and saw the changes automatically appear there. Was this a problem we had on Greenbiz.com on Deployment?

**Comment by andrewmallis** [comment]
I am pretty certain Pantheon does not do this.
There is a checkbox from the dashboard, but when we commit from github to Pantheon via the kalacommitbot (to DEV) the varnish cache does not get cleared.

For items that employ cache-busting like a new image resource we may see a change, but for HTML and other elements not so much.

**Comment by RobLoach** [comment]
Quicksilver will help this... Here are some examples:
https://github.com/pantheon-systems/quicksilver-examples

**Comment by andrewmallis** [comment]
Looks like we can also clear the cloudflare cache: https://github.com/pantheon-systems/quicksilver-examples/tree/master/cloudflare_cache
useful for GBZ!

**Comment by RobLoach** [comment]
https://pantheon.io/blog/move-stack-cloud-integration-tools-drupal-and-wordpress-developers
