### ISSUE TITLE
documentation funk

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#495]
http://kalastatic.readthedocs.io/en/latest/2-Components/

starting with **Component Sass**

there seems to be a syntax issue. Not sure.

**Comment by RobLoach** [comment]
http://kalastatic.readthedocs.io/en/latest/2-Components/#create-component still looks weird.

Perhaps split the 4th level headers into a bulleted list. Moving back to In Progress.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/506
