### ISSUE TITLE
roll in basic contact form implementation

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#5]
We've got a basic contact form working at
https://github.com/kalamuna/kalamuna.com/blob/master/templates/contact.html
and another at Pinnacle soon.

Let's pull a basic contact form into the kalastatic start state, and add a wiki page that talks about the form configuration, and points the appropriate documentation.

## QA

http://dev-kalastatic.at.kalamuna.com/contact/

**Comment by soniktrooth** [comment]
Hoping I wasn't stepping on toes but I started this.

**Comment by andrewmallis** [comment]
There's some re-architecting in your approach that I am not sure is the way we want to go. Everything is up for grabs, but @RobLoach has put together 2 contact pages in this framework to date, so is in the best position to feed back.

**Comment by RobLoach** [comment]
Thanks @soniktrooth

**Comment by andrewmallis** [comment]
Let's get this one in 0.3

**Comment by RobLoach** [comment]
@madeofpeople Sent up a PR for ya to help out with getting a filter for it: https://github.com/madeofpeople/metalsmith-swig-helpers/pull/5

**Comment by RobLoach** [comment]
http://dev-kalastatic.at.kalamuna.com/contact/

**Comment by andrewmallis** [comment]
email was set to kalastatic@example.com 

Created a PUBLIC group at kalastatic@kalamuna.com
