### ISSUE TITLE
document Drupal settings required to run

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#51]
When the prototype/styleguide exists alongside the Drupal theme, and is being committed as part of that repository, some modifications need be brought to the Drupal configuration itself: 

in .gitignore of the drupal stack, we need to add:

````
# KALASTATIC #
##############
node_modules
build
npm-debug.log
assets/vendor
````

and settings.php

```
// 7.21+ image hack for text-area images
// http://drupal.stackexchange.com/questions/63226/drupal-7-20-image-styles-return-a-url-with-access-denied
// this is likely required for the static prototype to render image files
$conf['image_allow_insecure_derivatives'] = TRUE;

```

This should be documented in the wiki.

**Comment by andrewmallis** [comment]
I can't recall what this is all about. Any memory of this @RobLoach

**Comment by andrewmallis** [comment]
This is for when the styleguide is rendered and pushed up inside the drupal repository…

**Comment by RobLoach** [comment]
Possible duplicate of https://github.com/kalamuna/kalastatic/issues/245

**Comment by andrewmallis** [comment]
Not so much a duplicate, but more specific in focus. I'm adding details there so we can close this one out.
