### ISSUE TITLE
Themes crash when .info file appears inside node_modules

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#52]
Some npm_modules contain .info files for test coverage

Building the prototype when in the drupal root causes drupal to blow up.
We get segfault errors in php and no real error reporting.
Awesome, Drupal!

see:
https://www.drupal.org/node/2329453
Themes should not crash when .info file appears inside node_modules

and proposed solution:
https://www.drupal.org/node/2309023#comment-9249847

which involves a post-commit hook on npm-install to remove the .info files

**Comment by andrewmallis** [comment]
While this is a hack, impact seems minimal.
Drupal should not do what it does here. We can document in the wiki, or a backlogged issue to revisit this approach.

**Comment by RobLoach** [comment]
Sent up a test to demonstrate the issue in Drupal:
https://www.drupal.org/node/2329453#comment-9569405
