### ISSUE TITLE
KSTAT Demo

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#535]
https://docs.google.com/presentation/d/1OkK1QMBwpki6eKGK5h6-YmXouqVVKoIJx2XVl3Phiho/edit#slide=id.g2d05bd447f_1_5

**Comment by thiagodemellobueno** [comment]
I pulled it up this morning to "get on that" ... but its night and day from yesterday, and quite frankly it's looking great!

**Comment by RobLoach** [comment]
https://youtu.be/vOc1nlUDyDo
