### ISSUE TITLE
Support kss namespaces in builder

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#558]
See line 49 here

https://github.com/kss-node/kss-node/blob/e90625ed2ab91778dadfd67b0d022184c60daaab/builder/base/twig/kss_builder_base_twig.js#L49

we can make sure to parse options passed into kalastatic (maybe)

**Comment by thiagodemellobueno** [comment]
I think this is where we can implement shared namespaces via kalstatic.yml

**Comment by RobLoach** [comment]
This should be working...
https://github.com/kalamuna/kalastatic/blob/master/docs/4-Prototyping.md#namespaces

Need to define them in the `kss` property.
