### ISSUE TITLE
Metalsmith web server access from other devices

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#57]
In building MTC I found that I was unable access 0.0.0.0:8000 from my iPhone on the same network or from Windows inside of VirtualBox. I was able to get to it from the Xcode iOS simulator. Is there something on the project we can adjust to have the web server accessible on other devices for testing purposes? Alternatively if there is specific network config required, then we should make a wiki page for it.

**Comment by andrewmallis** [comment]
we experimented with this at some point:
http://www.browsersync.io/
@madeofpeople is very interested in this.

In the interim, I think you can edit your router port forwarding configuration to point all incoming traffic requests across port 8000 to point to your computer IP. You'd benefit from reserving in IP based on your MAC address in the router, or DHCP will switch you out. Alternatively, you can switch from DHCP to DHCP with manual address in OS X system preferences.

I haven't tested this with kalastatic, so this remains theoretical.

**Comment by andrewmallis** [comment]
@madeofpeople reports that kalamuna.com has some of this.

#14 applies

**Comment by madeofpeople** [comment]
I created a tiny bit of documentation here: https://github.com/kalamuna/kalastatic/wiki/Testing-via-other-devices

**Comment by soniktrooth** [comment]
I already have port 80 forwarded to me so, will be easy to add 8000. For local networking on OS X it seems that %localhostname%.local:8000 does the trick. Where %localhostname% is replaced by your Mac's local host name

**Comment by madeofpeople** [comment]
I didn’t need to do any special routing.

**Comment by andrewmallis** [comment]
tested this in-office and can confirm this is working for the k2g project

**Comment by soniktrooth** [comment]
The original intent of this issue was anwered, @andrewmallis do you want to open a separate issue for browsersync if you think that's still a 'nice to have'

**Comment by madeofpeople** [comment]
I'll create it in the backlog, not priority, but kindanice.

**Comment by RobLoach** [comment]
https://localtunnel.me

```
lt --port 8000
your url is: https://gqgh.localtunnel.me
```
