### ISSUE TITLE
use relative paths for resources

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#58]
The guide can live in different places.]
css, js, images use absolute paths.
We're dealing with this over here: https://github.com/kalamuna/k2g/issues/9
and should seek to bring it back.

**Comment by madeofpeople** [comment]
So what we did in k2g in the end, puts the node server webroot at ../ so that build/ points to the prototype and build/styleguide points to the styleguide, this may not be the final solution but related to #75 #70 #65

**Comment by RobLoach** [comment]
basePath for the templating would be handy. Maybe in the configuration.

**Comment by andrewmallis** [comment]
see also #62 - redux in relation to kalatheme

**Comment by madeofpeople** [comment]
This is done no?

**Comment by andrewmallis** [comment]
yeah, I believe the scope of this is satisfied and satisfactory.
