### ISSUE TITLE
provide more modular navigation code

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#6]
Can we provide the header and footer navs in partials?

This would let us maintain a few nav options that can be selected from in the main templates.

We'd likely want to break navigation links out into markdown files too.

This is how we did it here: https://github.com/kalamuna/kalamuna.com/blob/master/templates/partials/header.html

**Comment by madeofpeople** [comment]
@andrewmallis i agree.

Question do you think it the loop needs its own partial template file?
Or should be a part of html.html?

It can be implemented in 15 mins.

**Comment by madeofpeople** [comment]
Fixed by #21
