### ISSUE TITLE
Document browsersync usage

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#61]
A nice to have.... makes testing easier.

**Comment by madeofpeople** [comment]
@RobLoach lets make sure we're not compiling bootstrap and jquery into our scripts.js but instead are pulling them in separately in html.html so that there is no need to retool in the case of kstatic being used for Drupal prototyping.

**Comment by andrewmallis** [comment]
@RobLoach notes that this can slow down the build

**Comment by RobLoach** [comment]
It's in. It was slow, but they've fixed it up a lot since.

**Comment by RobLoach** [comment]
Add docs.

**Comment by madeofpeople** [comment]
Done here https://github.com/kalamuna/kalastatic/wiki/BrowserSync

**Comment by andrewmallis** [comment]
made a small edit to the last line.
