### ISSUE TITLE
Redux in relation to kalatheme

### ISSUE THREAD

**Issue by thiagodemellobueno** [kalamuna/kalastatic#62]
So as we implement our first Kalatheme/Kalastatic hybrid, we learn things.
Currently putting kalastatic in the theme root is a bit noisy for Drupal folks, we're cluttering up the space, theres discussion of moving it into THEMEROOT/kalastatic
which works.

There are however implications re: relative paths and such, as well as assets.

Currently kalastatic favors the metalsmith purity approach for things like compiling assets and sass... this is smart, it keeps things simple, but when we merge with a Drupal theme, kinks in the armor show.

We dont want the drupal theme serving up THEMEROOT/kalastatic/build/css/main.css (do we?)

Will the mighty symlink save us here? In what situations is this not enough? 
- We could just compile the css in THEMEROOT/css but then the node-dev server can't load the css... 
- We can make it so you need to run a Kalastack for dev, but thats a somewhat heavy solution for things requiring only kalastack.
- We can have a watch task take the compiled css and make a copy in THEMEROOT/css

In all these cases we want to make sure we're maintaining only ONE set of scripts running the sass compile, or maintainability will suffer greatly.

**Comment by madeofpeople** [comment]
Basically how do we solve these issues while keeping Kalastatic something that can be used standalone also.

**Comment by andrewmallis** [comment]
Maybe something like this:
 
sites/all/themes/kalatheme
sites/all/themes/kalatheme_subtheme
sites/all/themes/kalastatic

where we build the CSS into kalastatic, but also build it into the theme.
A little bit of duplication, but avoids the symlinks, but expresses the modularity more cleanly, plus the projects play nice and are maintained/updated independently.

We're likely going to want to use drupal's menu callback structure to limit who can see the prototype and styleguide. It could be mighty confusing if someone hit the static homepage via google; they'd think they're in the site. This would require a small module, perhaps kalastatic_tools or kalatheme_tools – in which we could do other fancy things too.

**Comment by pirog** [comment]
a little more radical idea... you could consider building the styleguide out on a completely different site instead of embedding it within a drupal install. In the build you might need to carry along some drupal assets but then the layer for that is in the build and not either the source or dest repo. 

I think this might alleviate a lot of the technical concerns but would provide some admin overhead... depending on where you want these styleguides to live ie another pantheon instance/our own machine?

**Comment by madeofpeople** [comment]
I actually generally agree (they should live somewhere where clients can review) and feel that would simplify things mike.

The only thing is that then the scss needs to be manually (or CLIy) copied over as opposed to just being the same thing, whereas this more 'coupled' method lets them be the same thing, as we get to documenting how we want to set up our HTML so that it begins to be the same we expect out drupal (will just take doing this a couple of times, and documenting recurring patterns) that will hel us work rapidly.

But I see your point.

**Comment by andrewmallis** [comment]
The ability to see regressions in the styleguide when the theme is being worked on is rather powerful. There'd likely a way to still have that happen in decoupled environments, or by promoting that locally.

Canonical styleguide could live on github pages vs another pantheon instance…

**Comment by madeofpeople** [comment]
@andrewmallis excellent point re: regression testing.
But yeah, thats really a matter of passing the compiled main.css into the live build.
The GH pages is a good idea, there is the issue of paths and such which we should kind of figure out conceptually before moving on.

**Comment by soniktrooth** [comment]
Would it help any to have the style guide live in Drupal root instead of theme root? That way it could still easily reference the css and other Druapl assets Mike mentioned.

**Comment by madeofpeople** [comment]
Well then suddenly very clearly theme-y things are living in very much the wrong place.
Some potnetially causing larger problems.

Althought they could still build into the theme directory (easy to do in the metalsmith.json).
This would allow them to be two totally different repos… and just the themers pull the ‘kalastatic-drupal-theme-builder’ in.

Intriguing, but frought with peril (and then the source doesnt live in the theme)

**Comment by madeofpeople** [comment]
Jquery and boostral js are being loaded in html.html (so we can just load up compiled js into a drupal site without issue).

**Comment by madeofpeople** [comment]
#134  (base url) plays a role here

**Comment by RobLoach** [comment]
> #134 (base url) plays a role here

Yup! That would help... Base URL would end up being `/sites/all/themes/mytheme`.

I also put together a brain dump at https://github.com/kalamuna/kalastatic/issues/141 , which touches on a bunch of points. The biggest one being KalaStatic becoming more of a framework than a boilerplate project. Being a usage product, which comes with the configuration needed to do all the heavy-lifting. Would make leveraging a theme with it much easier.

**Comment by andrewmallis** [comment]
https://github.com/kalamuna/kalastatic-cli may help us out here

**Comment by madeofpeople** [comment]
A conversation between Josh and I regarding some kalatheme/kalastatic ecosystem.

https://docs.google.com/document/d/1g-GK5PTA4_pmxLdWF5VGdefWNBX4rfdF9EaJBycUkiY/edit

**Comment by madeofpeople** [comment]
@soniktrooth has some new insights here from casper. 
And we should do some planning around the 'co existing within a drupal site'

the base_url issue #134  plays a role here for sure.

**Comment by andrewmallis** [comment]
https://github.com/kalamuna/casperguide

**Comment by andrewmallis** [comment]
@RobLoach – what's this all about:
https://github.com/kalamuna/kalastatic/blob/master/package.json#L72
and will this need to go away in the context of the module model?

**Comment by RobLoach** [comment]
@andrewmallis In the template, there is the ability to flip the variable that's used depending on whether Drupal is installed or not. Thiago has demoed that at:
https://github.com/kalamuna/kalastatic/blob/master/templates/layouts/html.html#L4

All of package.json is loaded in as variables, so this lets us stick some environment-based variables in the package.json config.

**Comment by soniktrooth** [comment]
I feel like we're getting pretty close to this being done. #237 probably the last thing left for the Kalastatic/Kalatheme Voltroning to be complete.

**Comment by madeofpeople** [comment]
:+1: :+1: :+1: :+1: :+1: :+1:

**Comment by madeofpeople** [comment]
![volt](https://cloud.githubusercontent.com/assets/79221/12306031/af6c1906-ba05-11e5-84f1-25d1acb121b6.jpg)
