### ISSUE TITLE
provide a 404 page

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#7]

**Comment by andrewmallis** [comment]
@RobLoach how did we get the 404s to actually redirect on kalamuna.com?

**Comment by madeofpeople** [comment]
404s are a server level thing... 
In a node server you would set the 'fallback' to 404.
Apache server you would do either htaccess or conf.
Drupal has its trickeries.
So sort of depends on the hosting setup.

**Comment by labboy0276** [comment]
http://cnpmjs.org/package/agito-http-redirection

**Comment by madeofpeople** [comment]
Agito is a middleware router, not something we can count on specific hosting implementations to have.

I guess the main question is how do we expect to host these static sites in the future, and which setups do we want to support.

Then we can devise a solution based on that.

**Comment by labboy0276** [comment]
Apache:
ErrorDocument 404 http://www.kalamuna.com

Nginx:
error_page 404 http://www.kalamuna.com;

**Comment by andrewmallis** [comment]
The outcome I am looking for is  a template in the stack
+
a documented approach (1 ideally, more if appropriate) here:
https://github.com/kalamuna/kalastatic/wiki/handling-404s

I recall us doing something with a metalsmith plugin or some other in-prototype solution. I don't think this made it to production.

On pantheon we can do things with settings.php. I think this loads even if no Drupal.

Here is what I see now, using index.php:
https://github.com/kalamuna/kalamuna.com/blob/86dfaefcf7e719a37cb951bc9095ad2ad23bb861/static/index.php

**Comment by andrewmallis** [comment]
added a not to
https://github.com/kalamuna/kalastatic/wiki/Handling-404-pages
that the 404s won't work locally.

@RobLoach is our 404 method here up to date?
It's probably valuable to be able to see the 404 page in development
