### ISSUE TITLE
Vendor code in src is problematic

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#70]
### Problem

Having Bower install third party code into the `src` directory (instructed by [.bowerrc](https://github.com/kalamuna/kalastatic/blob/master/.bowerrc)) is problematic. While it is handy as it means linking to vendor code can be relative paths, it has major draw-backs, like we saw in `k2g` where Font Awesome was outputting a `css/font-awesome.css` file. The reason for this is because Metalsmith then processes/parses the third-party vendor files. Metalsmith assumes it's our own stuff, taking action on it in ways we don't expect.

### Solution

Move it back to `assets/vendor`, and correct the paths that reference the third-party code incorrectly...

#### 1. Font-Awesome
Node-SASS doesn't rebase @import paths, so in order to fix the font paths, we can change the `$fa-font-path` to reference `/vendor/fontawesome/fonts`. Since `$fa-font-path` is defined as a default, it will then reference the correct path.

#### 2. Other locations?
There may be a couple others, but it's easily fixed. We just need to go through and make sure node-sass behaves correctly.

**Comment by madeofpeople** [comment]
The main issue here is that we cant then use metalsmith-concat with the js files in vendor. This is fine if we compile the concated or concated/uglified js with a preprocessor (either just node-sass and plain ol concat)... no reason not to.

I am thinking that using "metalsmith for everything" is less prefereable than compiling assets (both css and js) via say, npm or grunt and move it into assets.

**Comment by madeofpeople** [comment]
Although there has been some desire to move the JS concatenation/packaging to browserify, which we ought do. But that leaves the strategy described very much the same... compile using a proper tool, move to assets, let metalsmith assets do the ingestion.

**Comment by madeofpeople** [comment]
This is resolved I think.
We're seeing eye to eye on this now :dancer:
