### ISSUE TITLE
Add mobile friendly favicons.

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#72]
I hit my head against this in the past.
Here's a truly cross browser solution
```
<link rel="shortcut icon" href="{PATHTO}/favicon.ico" type="image/vnd.microsoft.icon">
<link rel="apple-touch-icon" href="/touch-icon.png">
<link rel="icon" href="/favicon.png">
<!--[if IE]><link rel="shortcut icon" href="/favicon.ico"><![endif]-->
<!-- or, set /favicon.ico for IE10 win -->
<meta name="msapplication-TileColor" content="#f00">
<meta name="msapplication-TileImage" content="/tileicon.png">
```

**Comment by soniktrooth** [comment]
This looks good. @madeofpeople are you going to do a PR for this?

**Comment by madeofpeople** [comment]
Just documenting for now, glad to do it, but first come first serve ;)

**Comment by soniktrooth** [comment]
Ok, I'm opening a branch for this. 

Also I've used this before with some success: http://realfavicongenerator.net/

You can throw a png at it and it will give you back all the images you need at different sizes for all the platforms.

Only thing is I need access to a bigger version of the Kalamuna logo that what I can find on the interwebs atm. 

@andrewmallis are you able to hook me up with an .eps version or something?

**Comment by madeofpeople** [comment]
Hey josh they are all on the google drive, let me make sure you're shared on it.

**Comment by madeofpeople** [comment]
That's

```
LARGE HEADLINE
----------   ----------
 Link        Link
 Title        Title
 Blurb      Blurb
----------   ----------
-----------------------
Link Title 
Blurb
-----------------------
```

**Comment by soniktrooth** [comment]
So I ran the Kalalogo through the favicon generator and it's recommending the following. 

```
<link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/manifest.json">
<meta name="msapplication-TileColor" content="#ffc40d">
<meta name="msapplication-TileImage" content="/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">
```

This seems quite verbose. Obviously they're covering all bases but not sure if we really want to be this thorough. 

Thoughts @madeofpeople @andrewmallis?

**Comment by madeofpeople** [comment]
Dont see why not

On February 24, 2015 4:47:00 PM EST, Josh <notifications@github.com> wrote:
>So I ran the Kalalogo through the favicon generator and it's
>recommending the following. 
>
>```
><link rel="apple-touch-icon" sizes="57x57"
>href="/apple-touch-icon-57x57.png">
><link rel="apple-touch-icon" sizes="60x60"
>href="/apple-touch-icon-60x60.png">
><link rel="apple-touch-icon" sizes="72x72"
>href="/apple-touch-icon-72x72.png">
><link rel="apple-touch-icon" sizes="76x76"
>href="/apple-touch-icon-76x76.png">
><link rel="apple-touch-icon" sizes="114x114"
>href="/apple-touch-icon-114x114.png">
><link rel="apple-touch-icon" sizes="120x120"
>href="/apple-touch-icon-120x120.png">
><link rel="apple-touch-icon" sizes="144x144"
>href="/apple-touch-icon-144x144.png">
><link rel="apple-touch-icon" sizes="152x152"
>href="/apple-touch-icon-152x152.png">
><link rel="apple-touch-icon" sizes="180x180"
>href="/apple-touch-icon-180x180.png">
><link rel="icon" type="image/png" href="/favicon-32x32.png"
>sizes="32x32">
><link rel="icon" type="image/png" href="/android-chrome-192x192.png"
>sizes="192x192">
><link rel="icon" type="image/png" href="/favicon-96x96.png"
>sizes="96x96">
><link rel="icon" type="image/png" href="/favicon-16x16.png"
>sizes="16x16">
><link rel="manifest" href="/manifest.json">
><meta name="msapplication-TileColor" content="#ffc40d">
><meta name="msapplication-TileImage" content="/mstile-144x144.png">
><meta name="theme-color" content="#ffffff">
>```
>
>This seems quite verbose. Obviously they're covering all bases but not
>sure if we really want to be this thorough. 
>
>Thoughts @madeofpeople @andrewmallis? 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/kalamuna/kalastatic/issues/72#issuecomment-75853456

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andrewmallis** [comment]
We should exercise some restraint in order to represent the project focus.
Adds a lot of code and files to a stack whose primary purpose is to prototype.

Drupal, WP, the CMS should take care of this for us.

We did name the project kalastatic, so there is an expectation, there…

I am concerned that we're next going to be be debating how robust our metadata needs to be, and fall down a semantic/best practice rabbit hole and more gotchas to maintain than necessary.

Here is a good guide on what's really necessary:
https://github.com/audreyr/favicon-cheat-sheet

Would propose we cut out much of the fluff. How many users are creating homescreen shortcuts on their first generation iPad to a website?

**Comment by soniktrooth** [comment]
@andrewmallis that's what I meant by not being so thorough. This project is about getting a site up and running quickly, not about supporting as many legacy incarnations as possible. 

An example from another area of the project:
We're using Bootstrap without any shivs. This means we're actively ignoring IE8 and below for styling/layout. This doesn't matter because if Kalastatic is used for a site that needs IE8 support then shivs can be added in that particular project.

**Comment by soniktrooth** [comment]
Ok, I stripped it back as per the suggestions on that cheat sheet. 

@madeofpeople can you make a case for these MS proprietary looking ones you included originally? I'm happy to support the Windoze, but unless there's a real need we can run with out.

```
<link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon"> 
<!--[if IE]><link rel="shortcut icon" href="/favicon.ico"><![endif]-->
<!-- or, set /favicon.ico for IE10 win -->
```

**Comment by madeofpeople** [comment]
Fine points re: focus, which I'm generally fine with.

My only case for those is that it's actually easy to do, and documented. And should we ever push another static site for whatever reason, we'll need to tackle these issues eventually.

That said, its defnitely not a 1.0 feature, and doesnt support our primary use case.

**Comment by soniktrooth** [comment]
@madeofpeople Do you know functionally what they do? Is it for Metro live tiles or some such thing?

**Comment by madeofpeople** [comment]
@josh thatIsCorrectSir™

**Comment by andrewmallis** [comment]
In the scope of kalastatic we are limiting our icon usage.

**Comment by soniktrooth** [comment]
In this case perhaps we can just park this issue?
