### ISSUE TITLE
Incorporate OpenGraph metatags for the socialweb

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#73]
pseudocode, will require us to define what our baseline YAML frontmatter might be, discuss.

```
<link rel="canonical" href="http://{CANNONICAL_URL}/">
<link rel="shortlink" href="http://{USUALLY_CANNONICAL_URL}/">
<meta property="og:site_name" content="{SITENAME}">
<meta property="og:type" content="website">
<meta property="og:url" content="{CURRENT_PAGE_URL}">
<meta property="og:title" content="{PAGE_TITLE}">
<meta property="og:description" content="{PAGE_DESCRIPTION_OR_EXCERPT}">
<meta property="og:image" content="{PAGE_LEVEL_IMAGE}">
```

**Comment by soniktrooth** [comment]
I don't feel like I know enough about OpenGraph to be helpful here

**Comment by madeofpeople** [comment]
Well those tags above would just make it so sites like facebook can show pretty previews.
Just documenting for now, since there are considerations (such as adding thumbs) and the YAML schema require a little bit of thought before going ahead and executing.

**Comment by madeofpeople** [comment]
As per #72 lets shelf this for now.
