### ISSUE TITLE
Versioning strategy 1.0

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#74]
Deployment methods and structures should be apparent from the version of kalastatic. How do we pair this against kalatheme.

http://semver.org

**Comment by RobLoach** [comment]
:+1:

**Comment by pirog** [comment]
+1

On Wednesday, February 11, 2015, Rob Loach <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/74#issuecomment-73959947>.
>


-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
We currently have a 1.0 milestone.
It would be swell to have a demo site that, in the footer perhaps says which version of kalastatic is demonstrated.

It would be good to start tagging before we reach 1.0, so we can feel progress.
Where do y'all feel we are at now?

0.1.x ?
0.2.x ?
?.?.?

**Comment by pirog** [comment]
if it is helpful at all the strategy we are using for kalabox is

1. every merge into master increments the patch version by 1.
2. We manually bump the minor version when completion of a "dev cycle with
known motif" happens. we git tag here.
3. We bump the major version when we have reached pure zen or when we agree
that no more major features will be released.

On Fri, Feb 20, 2015 at 2:53 PM, Andrew_Mallis <notifications@github.com>
wrote:

> We currently have a 1.0 milestone.
> It would be swell to have a demo site that, in the footer perhaps says
> which version of kalastatic is demonstrated.
>
> It would be good to start tagging before we reach 1.0, so we can feel
> progress.
> Where do y'all feel we are at now?
>
> 0.1.x ?
> 0.2.x ?
> ?.?.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/74#issuecomment-75334554>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by andrewmallis** [comment]
I like the idea of merge to master incrementing the patch version by 1 via the CI.
We could also increment our proposed global vars too mentioned in #47/

**Comment by andrewmallis** [comment]
we've agreed to kick this off starting with 0.2.5

**Comment by andrewmallis** [comment]
moving this to 0.3 so we can shore up the docs.

**Comment by madeofpeople** [comment]
#98

**Comment by RobLoach** [comment]
Josh, Thiago and I discussed this today. While versioning is important, we don't think it is a problem at this point. We can re-discuss in the future while adoption is higher.

**Comment by pirog** [comment]
From the kalabox experience, doing auto-version bumping for patches has probably been only a slight net positive FWIW. it does add some extra noise to the collaboration.

**Comment by andrewmallis** [comment]
So, we are using Kalastatic on a number of production builds at this point. 
We should make more explicit which version we are running.

Our last release was 0.5 on on Sep 28, 2015
https://github.com/kalamuna/kalastatic/releases

We are way ahead of that!

It would be really good to have a version appear in ``package.json`` and/or ``README.md`` so people downloading and using kalastatic can report back on what version they are using in bug reports, including us.

**Comment by RobLoach** [comment]
Tag the thing, and doc it.

**Comment by andrewmallis** [comment]
Let's jump to 0.6.0

**Comment by RobLoach** [comment]
Take a look at DEV/TEST and make sure they're good.

**Comment by RobLoach** [comment]
Tagged 0.6.0, and added Docs in https://github.com/kalamuna/kalastatic/pull/273

**Comment by RobLoach** [comment]
No `-dev`.
