### ISSUE TITLE
JS Packaging

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#77]
Related to #75  and #70 

Webpack?
Browserify?
Duo?
Systemjs?

**Comment by madeofpeople** [comment]
I'm digging on duo because of require(http://somegitrepourl) which removes bower from the workflow (one less thing!)

**Comment by RobLoach** [comment]
![keepcalmandpackagemanagers](https://cloud.githubusercontent.com/assets/25086/6258126/f7d4b074-b793-11e4-9881-1886af89fb83.png)

**Comment by RobLoach** [comment]
#65
