### ISSUE TITLE
Gardener needed

### ISSUE THREAD

**Issue by soniktrooth** [kalamuna/kalastatic#78]
Too many branches. Prune all the things.

**Comment by soniktrooth** [comment]
:smile_cat:

**Comment by pirog** [comment]
+1

On Wed, Feb 18, 2015 at 2:29 PM, Josh <notifications@github.com> wrote:

> [image: :smile_cat:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/78#issuecomment-74962424>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by RobLoach** [comment]
![selfie-1](http://i.imgur.com/7I9crHM.png)

**Comment by pirog** [comment]
marry me

On Wed, Feb 18, 2015 at 2:34 PM, Rob Loach <notifications@github.com> wrote:

> [image: selfie-1]
> <https://camo.githubusercontent.com/4c83165de6ba2ace8c809aed52004fcf5746f8d4/687474703a2f2f692e696d6775722e636f6d2f3749396372484d2e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalamuna/kalastatic/issues/78#issuecomment-74963269>.
>



-- 
Cheers,

Mike Pirog
Kalamuna
www.kalamuna.com

**Comment by RobLoach** [comment]
I'd consider this complete. Have three branches, all with commits ahead of master, ready to pull in.
