### ISSUE TITLE
Improve support for variation of layout and functionality

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#8]
metalsmith.json provides configuration of our collections.
We're setting up some patterns that may or may not be used, and it could be useful to retain these patterns for optional inclusion.

The json standard does not support comments, but there is a grunt package that can be used to rip these out: https://www.npmjs.com/package/grunt-strip-json-comments

_Some treatments that vary:_
- Headers
- Footers
- Blog/News
- Templates
## SEE also
- https://github.com/kalamuna/kalastatic/wiki/Approach-Focus-and-Direction
- https://github.com/kalamuna/kalastatic/wiki/project-configurations

**Comment by andrewmallis** [comment]
@RobLoach – what do you think of this?

**Comment by soniktrooth** [comment]
oh fancy!

**Comment by madeofpeople** [comment]
IMHO it would be better to store metalsmith-{useCase}-example.json files in the general repo for this use case, as opposed to create grunt tooling to add/remove comments from json files (which json files don't allow for).

**Comment by madeofpeople** [comment]
Basically it solves the propblem of storing useful patterns, without creating an additional layer of abstraction and complexity of onboarding....

**Comment by RobLoach** [comment]
This is a non-issue in KSTAT2.

**Comment by thiagodemellobueno** [comment]
Agreed. I think it was more of an idea when kalastatic was going to be some configurable boilerplates... but it is not anymore.

Close!
