### ISSUE TITLE
Component conventions

### ISSUE THREAD

**Issue by madeofpeople** [kalamuna/kalastatic#84]
We should take what we can from something like this:
http://webcomponents.org/

**Comment by madeofpeople** [comment]
And there is also: http://patternlab.io/


Using this https://github.com/snugug/eq.js will also allow us to keep our CSS super modular.
@soniktrooth agrees.

**Comment by andrewmallis** [comment]
and there is also http://absurdjs.com that @RobLoach agrees with.

**Comment by madeofpeople** [comment]
Phase2 is using patternlab these days.... they provided a pretty nifty session in LA.

**Comment by madeofpeople** [comment]
#167
