### ISSUE TITLE
styleguide side navigation renders inline

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#87]
![bootstrap_styleguide](https://cloud.githubusercontent.com/assets/249362/6310788/1ba5f400-b90f-11e4-9e93-073337201b86.png)

**Comment by soniktrooth** [comment]
Pretty sure this is fixed now.

**Comment by andrewmallis** [comment]
nope.

**Comment by soniktrooth** [comment]
I swear this was working earlier in the week. @RobLoach did you change anything to do with the KSS/styleguide? When I was looking at it earlier in the week it looked like it had the stuff that you did for kalamuna.com rolled in but now it seems to have reverted back to the way it was previously.

**Comment by RobLoach** [comment]
http://dev-kalastatic.at.kalamuna.com/styleguide/section-1.html
