### ISSUE TITLE
Switch templating engine from swig to Twig

### ISSUE THREAD

**Issue by RobLoach** [kalamuna/kalastatic#92]
- [Twig](https://github.com/twigphp/Twig) - Drupal-side
- [Twig.js](https://github.com/twigjs/twig.js) - Prototype/Styleguide
- [KSS Docs to on `--extend-drupal8`](https://github.com/kss-node/kss-node#using-the-command-line-tool)

**Comment by madeofpeople** [comment]
Could you break down what some of the benefits over swig might be?

I do like jade, and it's syntax, it supports partials and inheritance in the same way swig does (which was the main reason for choosing it over handlebars) ... it maybe harder to onboard (but not that hard).


atpl hasnt received any commits in 7 months, few issues or pull requests filed or responded to and sports 22 stars and 4 forks. Id say its a no go.

**Comment by RobLoach** [comment]
https://github.com/mozilla/nunjucks

**Comment by madeofpeople** [comment]
So 
nunjucks is pretty cool, and rather straightforward to set up, it has a nice truncate filter (like we were doing with limit)

There are a couple filters we're going to need to port
* slug (a string becomes | a-string-becomes)
* xor (robs email obfuscation)
* isSlugMatch ( a string == a-string)  we use this for active nav items
* bustcache ( {{ aPath.jpg|bustcache}} becomes aPath.jpg?millisecondsSinceUnixEpoc

Shouldnt be too hard, 
https://mozilla.github.io/nunjucks/api#custom-filters
(pretty much the same as we've done with swig)

In searching around I found this https://github.com/nymag/nunjucks-filters
We could contribute to it, and send PRs, but it is lacking the specific filters we need.
So we would be adding a bunch of stuff to the contribute a few filters towards.
That said it is maintained by nymag, so its probably actively kept up, I would feel better about it if they were using underscore.string for stuff.

**Comment by madeofpeople** [comment]
Hmmm twig js supports pretty much all the things we need
https://github.com/justjohn/twig.js/wiki/Implementation-Notes

slug xor isSlugMatch and bustcache would also have to be recreated... but given drupal 8 it's probably the way to go non?

syntax wise I see no appreciable difference.

Nunjucks has Mozilla behind it though and that maybe a big consideration.
(Though swig.js seems like a healthy and active project)

**Comment by andrewmallis** [comment]
we should probably create smaller issues to recreate the filters

**Comment by madeofpeople** [comment]
But there's benefit to discussing here before then.

The two main issues aside from creating the custom filters is: 

A. Will the paths change? (not a big deal, more an issue of whether they do things differently)

B. Swig as a global made it really easy to set up the filters... https://github.com/madeofpeople/metalsmith-swig-helpers/blob/master/lib/index.js
Is the same true for twig?  if it is, things should be quite easy: https://github.com/justjohn/twig.js/wiki/Extending-twig.js

C. We should make each filter a standalone npm probject (when in node do as the noders do).

**Comment by madeofpeople** [comment]
Danger will robinson: https://github.com/justjohn/twig.js/issues/234

**Comment by madeofpeople** [comment]
Although: https://github.com/540/metalsmith-twig/blob/master/lib/index.js

**Comment by andrewmallis** [comment]
Agreed @madeofpeople – let's keep the discussion going before we fire up more granular issues. I've even updated the title to reflect the issue being a tad less actionable for now.

**Comment by madeofpeople** [comment]
So given consolidate's lack of twigjs support 
(@RobLoach did some solid work with a PR, but its an as yet incomplete implementation (local variables only))

Which makes me think that despite it all, we maybe want to stick to nunjucks.

**Comment by RobLoach** [comment]
1. Define Twig components
2. Use KSS Twig Builder to build out the styleguide using those components
3. Use Twig components in the prototype
4. Make use of the Twig components from Drupal using a TwigBridge

**Comment by thiagodemellobueno** [comment]
On this front I've upgraded our swig filters and contributed to a few packages…

Metalsmith Kalastatic Twig Filters (a metalsmith plugin that leverages the now more generic kalastatic-twig-filters)
https://github.com/kalamuna/metalsmith-kalastatic-twig-filters

The above mentioned node plugin:
https://github.com/kalamuna/kalastatic-twig-filters

This required a small tweak to metalsmith-twig:
https://github.com/thiagodemellobueno/metalsmith-twig

Open PR for that change lives here:
https://github.com/PKuebler/metalsmith-twig/pull/9

@RobLoach curious for you to review, if this stuff is all kosher, we are in TwigLand™

**Comment by thiagodemellobueno** [comment]
So this hasn't been ported to a Kalastatic pull request, but can be considered "done" in both 1.0 and 2.0 at this juncture.

Rob would love to get the prototyping bit going with the next in a PR branch.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kss-bootstrap/pull/43

**Comment by RobLoach** [comment]
We're did done.
