### ISSUE TITLE
Provide basic prismic integration for news

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#94]
#10 seeks to more broadly improve the content authoring experience.
Here we are looking to connect more directly with the [Prismic](https://prismic.io) content authoring service.

https://kalastatic.prismic.io/
provides some existing [masks](https://kalastatic.prismic.io/settings/masks) in json.

metalsmith plug-in: https://www.npmjs.com/package/metalsmith-prismic

Let's target news initially. It's a pretty simple model.

**Comment by andrewmallis** [comment]
@RobLoach –
we have a branch here: https://github.com/kalamuna/kalastatic/tree/prismic
but no pull request just now.

I'd really like to get a demo-able prismic integration into master. 
Since our prismic repo is public, it should be a
https://developers.prismic.io/documentation/developers-manual

I also don't think we should 100% replace news for this example, but rather demonstrate a flavor. How about we set up 2 tabs for news examples: /news/#markdown example to a /news/#prismic in tabs.

**Comment by RobLoach** [comment]
https://github.com/kalamuna/kalastatic/pull/130/

**Comment by andrewmallis** [comment]
Let's multidev this:
https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#multidev/overview/git-branches

**Comment by RobLoach** [comment]
http://prismic-kalastatic.at.kalamuna.com/news/

**Comment by andrewmallis** [comment]
@RobLoach – I pushed a code change in #130 which passes Travis, but I don't see http://prismic-kalastatic.at.kalamuna.com/article/VPYOnCkAACA8Lm-E/about/ updated at
http://prismic-kalastatic.at.kalamuna.com/article/VPYOnCkAACA8Lm-E/about/
to reflect what I see in my local build.

**Comment by andrewmallis** [comment]
also, the prismic environment on pantheon:
https://dashboard.getpantheon.com/sites/99097056-c6bd-451e-a94b-fc8f7666fbe5#prismic/code
says its been merged to master, but we know that's not true.

**Comment by andrewmallis** [comment]
considering this done, since the issue does not seem to be with our code, here.

**Comment by RobLoach** [comment]
:+1:
