### ISSUE TITLE
provide integration with Pantheon multi-dev via the CI

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#95]
Not every feature branch requires upstream testing, but some do.

Pantheon provides environments _à la carte_ via its [multidev](https://pantheon.io/docs/articles/sites/multidev/) tool. We can spin up new environments from branches with [terminus](https://pantheon.io/docs/articles/local/terminus-the-pantheon-command-line-interface/)

Here is a Travis template proven to work:
https://gist.github.com/iamEAP/8855842
though this solution generates a random branch / multidev name, prefixed with "ci" followed by the Travis build number.

That'd be hard to find and sync up.

Let's explore an issue # instead that corresponds to a pull request?
We don't need to CI every upstream branch/

**Comment by RobLoach** [comment]
Just putting this in my own words....

> Allow created Pull Requests/Branches to deploy to Pantheon based on the name of the given branch.

**Comment by RobLoach** [comment]
Josh got a great idea... Have a private repository that's mirrored. Whenever our public repo (kalastatic) gets a commit, mirror it to the private one. Then have magnum.travis.com push to Pantheon.
