### ISSUE TITLE
serve site locally at 127.0.0.1 instead of 0.0.0.0

### ISSUE THREAD

**Issue by andrewmallis** [kalamuna/kalastatic#96]
Based on [RFC 5735](http://tools.ietf.org/html/rfc5735), 0.0.0.0 is non-routable.

Recently [Chrome stopped routing it to 'localhost' and searching the string "0.0.0.0" on Google instead.](https://code.google.com/p/chromium/issues/detail?id=428046)

127.0.0.1 is a more safe solution for the default address.

_via https://github.com/nodeapps/http-server/issues/128_

**Comment by madeofpeople** [comment]
This would prevent us being able to debug from mobile devices.
You can always point to 'localhost' or another alias in /etc/hosts (i used node.loc:8000)

**Comment by RobLoach** [comment]
https://github.com/gruntjs/grunt-contrib-connect#hostname

**Comment by andrewmallis** [comment]
localhost:8000 seems to work. Looks like chrome is not throwing up at 0.0.0.0 anymore as much either…
